"""Demo seed script — populates the full AYAZ app with realistic demo data.

Usage
-----
From the ``backend/`` directory:

    python -m scripts.seed_demo          # as a module
    python scripts/seed_demo.py          # as a script

The script is fully idempotent: running it multiple times will not duplicate
data.  It creates:

1. A demo Tenant (name "AYAZ Demo", base_currency "TRY").
2. A demo User (email ``demo@ayaz.app``, password ``demo12345``).
3. An owner Membership linking the user to the tenant.
4. Three ConnectedAccounts: google_ads, meta_ads, tiktok_ads.
5. 45 days of FactDailyMetrics for 3 channels x 2-3 campaigns each, with
   realistic baselines, mild noise, and injected anomalies in the last 7 days:
     - google_ads / "Brand Search"   : ROAS drop in days -6 to -1  (critical)
     - meta_ads  / "Retargeting"     : spend spike in days -5 to -1 (warning)
     - tiktok_ads / "Viral Creative" : zero conversions in days -7 to -1
6. A FeedSource ("Demo Ürün Feed'i") with products from sample_feed.xml, plus
   two FeedChannels (google_shopping XML + meta_catalog CSV) each with rules.
7. Insights generated by calling services.insights.generate_insights.
8. One ReportDefinition (white-label) with a SharedReport link (if the reports
   model is importable — guarded with try/except for forward-compat).

Connector fixtures
------------------
``sample``    — ``tests/fixtures/sample_metrics.json`` (3 rows, 2024-03)
``google_ads`` — ``tests/fixtures/google_ads_search_stream.json`` (3 rows, 2024-06)

The GoogleAdsConnector is used in *fixture mode*: we directly call
``normalize()`` on the pre-recorded fixture rather than calling ``fetch()``
(which would hit the real API).  We do this by subclassing GoogleAdsConnector
and overriding ``fetch()`` to load the local fixture instead.

Anomaly injection
-----------------
All fact values are generated deterministically via index-based arithmetic
(no random seed needed — same index always produces the same value).
Anomalies are injected by overriding the computed value for specific
(channel, campaign, day-offset) combinations in the last 7 days:
  - ROAS drop: conversion_value_raw halved on google_ads "Brand Search"
  - Spend spike: cost_raw tripled on meta_ads "Retargeting"
  - Zero conversions: conversions forced to 0 on tiktok_ads "Viral Creative"

Exit codes
----------
0 — success
1 — DB unreachable (prints the error and instructions)
"""

from __future__ import annotations

import json
import secrets
import sys
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path

# Ensure the backend package root is on sys.path when run as a plain script.
_BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(_BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(_BACKEND_DIR))

from sqlalchemy import select
from sqlalchemy.exc import OperationalError

from ayaz.connectors.base import ConnectorConfig
from ayaz.connectors.google_ads import GoogleAdsConnector
from ayaz.connectors.sample import SampleConnector
from ayaz.database import SessionLocal, engine
from ayaz.models.analytics import (  # noqa: F401 — ensure tables known
    DimChannel,
    DimCampaign,
    DimAdSet,
    DimAd,
    DimDate,
    FactDailyMetrics,
)
from ayaz.models.base import Base
from ayaz.models.feeds import FeedChannel, FeedProduct, FeedRule, FeedSource
from ayaz.models.oltp import (
    ConnectedAccount,
    Membership,
    MembershipRole,
    Platform,
    SyncStatus,
    Tenant,
    User,
)
from ayaz.services.auth import hash_password
from ayaz.services.feeds import ingest_feed_source
from ayaz.services.insights import generate_insights
from ayaz.services.sync import (
    _ensure_dim_date,
    _get_or_create_channel,
    _get_or_create_campaign,
    _get_or_create_adset,
    _get_or_create_ad,
    _upsert_fact,
    sync_connected_account,
)

# Reports model is guarded — may be absent in very early branches.
try:
    from ayaz.models.reports import ReportDefinition, SharedReport
    _REPORTS_AVAILABLE = True
except ImportError:
    _REPORTS_AVAILABLE = False

# ── Constants ─────────────────────────────────────────────────────────────────

DEMO_EMAIL = "demo@ayaz.app"
DEMO_PASSWORD = "demo12345"
DEMO_TENANT_NAME = "AYAZ Demo"
DEMO_CURRENCY = "TRY"

_FIXTURES_DIR = Path(__file__).resolve().parent.parent / "tests" / "fixtures"
_SAMPLE_FIXTURE = _FIXTURES_DIR / "sample_metrics.json"
_GOOGLE_ADS_FIXTURE = _FIXTURES_DIR / "google_ads_search_stream.json"
_FEED_FIXTURE = _FIXTURES_DIR / "sample_feed.xml"

# Date range for legacy fixture syncs (kept from original seed)
_SYNC_SINCE = date(2024, 1, 1)
_SYNC_UNTIL = date(2024, 12, 31)

# Rich fact data: 45 days ending 2026-06-25 (one day before today 2026-06-26)
_RICH_END_DATE = date(2026, 6, 25)
_RICH_START_DATE = _RICH_END_DATE - timedelta(days=44)  # 45 days inclusive
_ANOMALY_START_OFFSET = 38  # days from _RICH_START_DATE where anomalies begin (last 7 days)

# ── Channel / campaign definitions ────────────────────────────────────────────

# Each entry: (channel_key, platform_enum, account_external_id, account_display_name,
#              list of (campaign_ext_id, campaign_name, adset_ext_id, adset_name,
#                       ad_ext_id, ad_name,
#                       base_impressions, base_clicks, base_cost_try, base_conv, base_conv_val))
_CHANNEL_SPECS = [
    {
        "channel_key": "google_ads",
        "platform": Platform.google_ads,
        "account_ext_id": "GADS-DEMO-001",
        "account_display": "Google Ads — Demo Hesap",
        "cost_ccy": "TRY",
        "campaigns": [
            {
                "camp_ext": "G-CAMP-BRAND",
                "camp_name": "Brand Search",
                "adset_ext": "G-AS-BRAND-EXACT",
                "adset_name": "Marka Exact Match",
                "ad_ext": "G-AD-BRAND-RSA",
                "ad_name": "Marka RSA v1",
                # baselines per day
                "impressions": 12000,
                "clicks": 480,
                "cost": Decimal("1200.00"),
                "conversions": Decimal("24.0"),
                "conv_value": Decimal("6000.00"),
                # anomaly: ROAS drop — halve conv_value in last 7 days
                "anomaly": "roas_drop",
            },
            {
                "camp_ext": "G-CAMP-PRSP",
                "camp_name": "Prospecting — Genis Kitle",
                "adset_ext": "G-AS-PRSP-INT",
                "adset_name": "Ilgi Alanlari",
                "ad_ext": "G-AD-PRSP-DSA",
                "ad_name": "DSA Koleksiyon",
                "impressions": 45000,
                "clicks": 900,
                "cost": Decimal("2250.00"),
                "conversions": Decimal("18.0"),
                "conv_value": Decimal("5400.00"),
                "anomaly": None,
            },
            {
                "camp_ext": "G-CAMP-SHOP",
                "camp_name": "Shopping — Urun Listesi",
                "adset_ext": "G-AS-SHOP-ALL",
                "adset_name": "Tum Urunler",
                "ad_ext": "G-AD-SHOP-DYNA",
                "ad_name": "Dinamik Shopping",
                "impressions": 30000,
                "clicks": 600,
                "cost": Decimal("1800.00"),
                "conversions": Decimal("30.0"),
                "conv_value": Decimal("9000.00"),
                "anomaly": None,
            },
        ],
    },
    {
        "channel_key": "meta_ads",
        "platform": Platform.meta_ads,
        "account_ext_id": "META-DEMO-001",
        "account_display": "Meta Ads — Demo Hesap",
        "cost_ccy": "TRY",
        "campaigns": [
            {
                "camp_ext": "M-CAMP-RETG",
                "camp_name": "Retargeting — Sepet Terk",
                "adset_ext": "M-AS-RETG-7D",
                "adset_name": "7 Gunluk Ziyaretci",
                "ad_ext": "M-AD-RETG-CARO",
                "ad_name": "Carousel — Sepet Urunu",
                "impressions": 25000,
                "clicks": 750,
                "cost": Decimal("1875.00"),
                "conversions": Decimal("37.0"),
                "conv_value": Decimal("11100.00"),
                # anomaly: spend spike in last 7 days
                "anomaly": "spend_spike",
            },
            {
                "camp_ext": "M-CAMP-ACQST",
                "camp_name": "Musteri Kazanimi — LAL",
                "adset_ext": "M-AS-LAL-2PCT",
                "adset_name": "2pct Lookalike",
                "ad_ext": "M-AD-LAL-VID",
                "ad_name": "Video — Marka Hikayesi",
                "impressions": 60000,
                "clicks": 900,
                "cost": Decimal("2700.00"),
                "conversions": Decimal("27.0"),
                "conv_value": Decimal("8100.00"),
                "anomaly": None,
            },
        ],
    },
    {
        "channel_key": "tiktok_ads",
        "platform": Platform.tiktok_ads,
        "account_ext_id": "TTADS-DEMO-001",
        "account_display": "TikTok Ads — Demo Hesap",
        "cost_ccy": "TRY",
        "campaigns": [
            {
                "camp_ext": "TT-CAMP-VIRAL",
                "camp_name": "Viral Creative — Gen Z",
                "adset_ext": "TT-AS-VIRAL-18-24",
                "adset_name": "18-24 Yas",
                "ad_ext": "TT-AD-VIRAL-UGC",
                "ad_name": "UGC Video — Dans Challenge",
                "impressions": 80000,
                "clicks": 1600,
                "cost": Decimal("2000.00"),
                "conversions": Decimal("20.0"),
                "conv_value": Decimal("5000.00"),
                # anomaly: zero conversions in last 7 days
                "anomaly": "zero_conversions",
            },
            {
                "camp_ext": "TT-CAMP-SPARK",
                "camp_name": "Spark Ads — Influencer",
                "adset_ext": "TT-AS-SPARK-MID",
                "adset_name": "Mid-tier Influencer",
                "ad_ext": "TT-AD-SPARK-HAUL",
                "ad_name": "Haul Video — Moda",
                "impressions": 50000,
                "clicks": 1000,
                "cost": Decimal("1500.00"),
                "conversions": Decimal("15.0"),
                "conv_value": Decimal("3750.00"),
                "anomaly": None,
            },
        ],
    },
]


# ── Noise helper (deterministic, index-based) ──────────────────────────────────

def _noise(base: Decimal, day_index: int, campaign_index: int, scale: float = 0.12) -> Decimal:
    """Return a deterministic pseudo-noise perturbation around ``base``.

    Uses a repeating pattern derived from the day and campaign index —
    no random module, so results are identical on every run.

    Pattern: a 7-step sawtooth combined with a 11-step offset, giving a
    17-step cycle (coprime pair) that looks organic in a chart without
    needing a random seed.
    """
    # 7-step sawtooth: -3, -2, -1, 0, +1, +2, +3 (repeats)
    saw7 = ((day_index + campaign_index * 3) % 7) - 3   # range [-3, 3]
    # 11-step second wave
    saw11 = ((day_index * 2 + campaign_index) % 11) - 5  # range [-5, 5]
    # Normalise: combined range is -8..8, scale to [-scale, +scale]
    factor = Decimal(str((saw7 + saw11) / 8.0 * scale))
    return base * (Decimal("1") + factor)


# ── Fixture-backed GoogleAds connector ────────────────────────────────────────


class _FixtureGoogleAdsConnector(GoogleAdsConnector):
    """GoogleAdsConnector with fetch() replaced by fixture loading.

    Used by the seed script only — never registers itself in the ConnectorRegistry
    because ``platform_key`` is cleared at the class level so ``__init_subclass__``
    skips registration (only subclasses that define platform_key as a non-empty
    string are registered).
    No live network calls are made.
    """

    # Clear platform_key so __init_subclass__ skips registration
    platform_key = ""  # type: ignore[assignment]

    def __init__(self, config: ConnectorConfig, fixture_path: Path) -> None:
        super().__init__(config)
        self._fixture_path = fixture_path
        # Provide a dummy access token so _auth_headers() won't raise
        self._access_token = "fixture-mode-no-token"

    def fetch(self, stream: str, since: date, until: date):  # type: ignore[override]
        """Load the recorded fixture and return the flattened row list."""
        with self._fixture_path.open(encoding="utf-8") as fh:
            raw_body = json.load(fh)
        rows = self._parse_stream_response(raw_body)
        # Filter by date range
        filtered = [
            r for r in rows
            if since <= date.fromisoformat(r["segments"]["date"]) <= until
        ]
        return filtered

    def authenticate(self) -> None:  # type: ignore[override]
        """No-op in fixture mode."""

    def refresh_token(self) -> None:  # type: ignore[override]
        """No-op in fixture mode."""


# ── OLTP helpers ──────────────────────────────────────────────────────────────


def _get_or_create_tenant(db) -> Tenant:
    tenant = db.scalar(select(Tenant).where(Tenant.name == DEMO_TENANT_NAME))
    if tenant is None:
        tenant = Tenant(
            name=DEMO_TENANT_NAME,
            base_currency=DEMO_CURRENCY,
            country="TR",
            kvkk_region="TR",
        )
        db.add(tenant)
        db.flush()
        print(f"  Created tenant: {DEMO_TENANT_NAME} ({tenant.id})")
    else:
        print(f"  Tenant already exists: {DEMO_TENANT_NAME} ({tenant.id})")
    return tenant


def _get_or_create_user(db) -> User:
    user = db.scalar(select(User).where(User.email == DEMO_EMAIL))
    if user is None:
        user = User(
            email=DEMO_EMAIL,
            hashed_password=hash_password(DEMO_PASSWORD),
            full_name="AYAZ Demo User",
        )
        db.add(user)
        db.flush()
        print(f"  Created user: {DEMO_EMAIL} ({user.id})")
    else:
        print(f"  User already exists: {DEMO_EMAIL} ({user.id})")
    return user


def _get_or_create_membership(db, user: User, tenant: Tenant) -> Membership:
    membership = db.scalar(
        select(Membership).where(
            Membership.user_id == user.id,
            Membership.tenant_id == tenant.id,
        )
    )
    if membership is None:
        membership = Membership(
            user_id=user.id,
            tenant_id=tenant.id,
            role=MembershipRole.owner,
        )
        db.add(membership)
        db.flush()
        print("  Created owner membership")
    else:
        print("  Membership already exists")
    return membership


def _get_or_create_connected_account(
    db,
    tenant: Tenant,
    platform: Platform,
    external_id: str,
    display_name: str,
) -> ConnectedAccount:
    account = db.scalar(
        select(ConnectedAccount).where(
            ConnectedAccount.tenant_id == tenant.id,
            ConnectedAccount.platform == platform,
            ConnectedAccount.external_account_id == external_id,
        )
    )
    if account is None:
        account = ConnectedAccount(
            tenant_id=tenant.id,
            platform=platform,
            external_account_id=external_id,
            display_name=display_name,
            vault_secret_ref="",
            sync_status=SyncStatus.idle,
        )
        db.add(account)
        db.flush()
        print(f"  Created ConnectedAccount: {platform.value} / {external_id}")
    else:
        print(f"  ConnectedAccount already exists: {platform.value} / {external_id}")
    return account


# ── Rich fact data generation ─────────────────────────────────────────────────


def _seed_rich_facts(db, tenant: Tenant, accounts: dict[str, ConnectedAccount]) -> tuple[int, int]:
    """Generate 45 days of FactDailyMetrics across 3 channels with anomalies.

    Returns (inserted, updated) counts.
    """
    inserted = 0
    updated = 0
    now_utc = datetime.now(timezone.utc)

    date_range = [
        _RICH_START_DATE + timedelta(days=d)
        for d in range(45)
    ]

    for ch_idx, ch_spec in enumerate(_CHANNEL_SPECS):
        channel_key = ch_spec["channel_key"]
        channel = _get_or_create_channel(db, channel_key)
        account = accounts[channel_key]

        for camp_idx, camp in enumerate(ch_spec["campaigns"]):
            campaign = _get_or_create_campaign(
                db, tenant.id, channel,
                external_id=camp["camp_ext"],
                name=camp["camp_name"],
            )
            adset = _get_or_create_adset(
                db, tenant.id, campaign,
                external_id=camp["adset_ext"],
                name=camp["adset_name"],
            )
            ad = _get_or_create_ad(
                db, tenant.id, adset,
                external_id=camp["ad_ext"],
                name=camp["ad_name"],
            )

            for day_idx, d in enumerate(date_range):
                _ensure_dim_date(db, d)

                # Base values with deterministic noise
                impressions = int(_noise(Decimal(camp["impressions"]), day_idx, camp_idx))
                clicks = max(1, int(_noise(Decimal(camp["clicks"]), day_idx, camp_idx + 1)))
                cost = _noise(camp["cost"], day_idx, camp_idx + 2).quantize(Decimal("0.01"))
                conversions = _noise(camp["conversions"], day_idx, camp_idx + 3).quantize(Decimal("0.01"))
                conv_value = _noise(camp["conv_value"], day_idx, camp_idx + 4).quantize(Decimal("0.01"))

                # Clamp to reasonable minimums
                clicks = min(clicks, impressions)
                cost = max(Decimal("0.01"), cost)
                conversions = max(Decimal("0"), conversions)
                conv_value = max(Decimal("0"), conv_value)

                # ── Anomaly injection (last 7 days = day_idx >= _ANOMALY_START_OFFSET) ──
                in_anomaly_window = day_idx >= _ANOMALY_START_OFFSET

                if in_anomaly_window and camp.get("anomaly") == "roas_drop":
                    # ROAS drop on google_ads Brand Search: halve conversion value
                    conv_value = (conv_value * Decimal("0.35")).quantize(Decimal("0.01"))

                elif in_anomaly_window and camp.get("anomaly") == "spend_spike":
                    # Spend spike on meta_ads Retargeting: triple cost
                    cost = (cost * Decimal("3.2")).quantize(Decimal("0.01"))

                elif in_anomaly_window and camp.get("anomaly") == "zero_conversions":
                    # Zero conversions on tiktok_ads Viral Creative: conversions → 0
                    conversions = Decimal("0")
                    conv_value = Decimal("0")

                # Check if fact row already exists for this grain
                existing = db.scalar(
                    select(FactDailyMetrics).where(
                        FactDailyMetrics.tenant_id == tenant.id,
                        FactDailyMetrics.connected_account_id == account.id,
                        FactDailyMetrics.channel_id == channel.id,
                        FactDailyMetrics.campaign_id == campaign.id,
                        FactDailyMetrics.adset_id == adset.id,
                        FactDailyMetrics.ad_id == ad.id,
                        FactDailyMetrics.date_key == d,
                    )
                )

                if existing is None:
                    fact = FactDailyMetrics(
                        tenant_id=tenant.id,
                        connected_account_id=account.id,
                        channel_id=channel.id,
                        campaign_id=campaign.id,
                        adset_id=adset.id,
                        ad_id=ad.id,
                        date_key=d,
                        impressions=impressions,
                        clicks=clicks,
                        cost_raw=cost,
                        cost_ccy=ch_spec["cost_ccy"],
                        conversions=conversions,
                        conversion_value_raw=conv_value,
                        conversion_value_ccy=ch_spec["cost_ccy"],
                        # Placeholder: no FX conversion — base_ccy = raw
                        cost_base_ccy=cost,
                        conv_value_base_ccy=conv_value,
                        ingested_at=now_utc,
                    )
                    db.add(fact)
                    inserted += 1
                else:
                    existing.impressions = impressions
                    existing.clicks = clicks
                    existing.cost_raw = cost
                    existing.cost_ccy = ch_spec["cost_ccy"]
                    existing.conversions = conversions
                    existing.conversion_value_raw = conv_value
                    existing.conversion_value_ccy = ch_spec["cost_ccy"]
                    existing.cost_base_ccy = cost
                    existing.conv_value_base_ccy = conv_value
                    existing.ingested_at = now_utc
                    updated += 1

        # Flush per channel to keep memory bounded
        db.flush()

    db.commit()
    return inserted, updated


# ── Feed seeding ───────────────────────────────────────────────────────────────

# Stable tokens derived from a fixed prefix so they survive re-runs.
# (Not cryptographically random by design — they're just demo public URLs.)
_GOOGLE_FEED_TOKEN = "ayaz-demo-gshop-token-0000000001"
_META_FEED_TOKEN   = "ayaz-demo-meta-token-00000000001"


def _seed_feeds(db, tenant: Tenant) -> dict:
    """Create FeedSource, ingest products, and set up two FeedChannels with rules.

    Returns dict with counts.
    """
    counts = {"feed_sources": 0, "products": 0, "channels": 0, "rules": 0}

    # ── FeedSource ─────────────────────────────────────────────────────────
    feed_source = db.scalar(
        select(FeedSource).where(
            FeedSource.tenant_id == tenant.id,
            FeedSource.name == "Demo Urun Feed'i",
        )
    )
    if feed_source is None:
        feed_source = FeedSource(
            tenant_id=tenant.id,
            name="Demo Urun Feed'i",
            source_type="upload",
            source_url=None,
            status="pending",
            item_count=0,
        )
        db.add(feed_source)
        db.flush()
        print(f"  Created FeedSource: Demo Urun Feed'i ({feed_source.id})")
        counts["feed_sources"] = 1
    else:
        print(f"  FeedSource already exists: Demo Urun Feed'i ({feed_source.id})")

    # ── Ingest products from fixture XML ───────────────────────────────────
    if _FEED_FIXTURE.exists():
        raw_bytes = _FEED_FIXTURE.read_bytes()
        n_products = ingest_feed_source(db, feed_source, raw_bytes=raw_bytes)
        counts["products"] = n_products
        print(f"  Ingested {n_products} products from sample_feed.xml")
    else:
        print(f"  WARNING: fixture not found at {_FEED_FIXTURE} — skipping product ingest")

    # ── FeedChannel: Google Shopping XML ───────────────────────────────────
    gshop_channel = db.scalar(
        select(FeedChannel).where(
            FeedChannel.public_token == _GOOGLE_FEED_TOKEN
        )
    )
    if gshop_channel is None:
        gshop_channel = FeedChannel(
            tenant_id=tenant.id,
            feed_source_id=feed_source.id,
            name="Google Shopping — Tum Urunler",
            channel_type="google_shopping",
            output_format="xml",
            public_token=_GOOGLE_FEED_TOKEN,
            is_active=True,
        )
        db.add(gshop_channel)
        db.flush()
        print(f"  Created FeedChannel: google_shopping ({gshop_channel.id})")
        counts["channels"] += 1

        # Rule 1: filter out-of-stock products
        r1 = FeedRule(
            tenant_id=tenant.id,
            feed_channel_id=gshop_channel.id,
            position=1,
            rule_type="filter_include",
            config={
                "condition_field": "availability",
                "condition_op": "eq",
                "condition_value": "in stock",
            },
        )
        # Rule 2: append brand suffix to title
        r2 = FeedRule(
            tenant_id=tenant.id,
            feed_channel_id=gshop_channel.id,
            position=2,
            rule_type="calculated",
            config={
                "field": "title",
                "expression": "{title} | AYAZ Demo",
            },
        )
        db.add_all([r1, r2])
        db.flush()
        counts["rules"] += 2
    else:
        print(f"  FeedChannel google_shopping already exists ({gshop_channel.id})")

    # ── FeedChannel: Meta Catalog CSV ──────────────────────────────────────
    meta_channel = db.scalar(
        select(FeedChannel).where(
            FeedChannel.public_token == _META_FEED_TOKEN
        )
    )
    if meta_channel is None:
        meta_channel = FeedChannel(
            tenant_id=tenant.id,
            feed_source_id=feed_source.id,
            name="Meta Katalog — Aktif Urunler",
            channel_type="meta_catalog",
            output_format="csv",
            public_token=_META_FEED_TOKEN,
            is_active=True,
        )
        db.add(meta_channel)
        db.flush()
        print(f"  Created FeedChannel: meta_catalog ({meta_channel.id})")
        counts["channels"] += 1

        # Rule 1: force condition to "new" for Meta compliance
        r3 = FeedRule(
            tenant_id=tenant.id,
            feed_channel_id=meta_channel.id,
            position=1,
            rule_type="set_value",
            config={"field": "condition", "value": "new"},
        )
        # Rule 2: strip price unit suffix (Meta expects "149.99 USD" — already correct)
        r4 = FeedRule(
            tenant_id=tenant.id,
            feed_channel_id=meta_channel.id,
            position=2,
            rule_type="find_replace",
            config={
                "field": "price",
                "pattern": r"\s+USD$",
                "replacement": " USD",
                "use_regex": True,
            },
        )
        db.add_all([r3, r4])
        db.flush()
        counts["rules"] += 2
    else:
        print(f"  FeedChannel meta_catalog already exists ({meta_channel.id})")

    db.commit()
    return counts


# ── Report seeding ─────────────────────────────────────────────────────────────

_REPORT_NAME = "AYAZ Demo — Aylik Performans Raporu"
_SHARED_REPORT_TOKEN = "ayaz-demo-report-token-000000001"


def _seed_reports(db, tenant: Tenant, user: User) -> dict:
    """Create one ReportDefinition with a SharedReport link.

    Guarded by _REPORTS_AVAILABLE — safe to call even if reports module is absent.
    Returns dict with counts.
    """
    counts = {"report_definitions": 0, "shared_reports": 0}
    if not _REPORTS_AVAILABLE:
        print("  reports model not available — skipping")
        return counts

    report_def = db.scalar(
        select(ReportDefinition).where(
            ReportDefinition.tenant_id == tenant.id,
            ReportDefinition.name == _REPORT_NAME,
        )
    )
    if report_def is None:
        report_def = ReportDefinition(
            tenant_id=tenant.id,
            name=_REPORT_NAME,
            created_by=user.id,
            config={
                "metrics": [
                    "spend", "impressions", "clicks",
                    "conversions", "conversion_value",
                    "ctr", "cpc", "cpa", "roas",
                ],
                "channels": ["google_ads", "meta_ads", "tiktok_ads"],
                "date_range_preset": "last_30_days",
                "sections": ["totals", "by_channel", "timeseries", "insights"],
                "brand_name": "AYAZ Demo Markasi",
                "logo_url": "https://ayaz.app/static/logo.png",
                "primary_color": "#6C47FF",
            },
        )
        db.add(report_def)
        db.flush()
        print(f"  Created ReportDefinition: {_REPORT_NAME} ({report_def.id})")
        counts["report_definitions"] = 1
    else:
        print(f"  ReportDefinition already exists ({report_def.id})")

    shared = db.scalar(
        select(SharedReport).where(
            SharedReport.public_token == _SHARED_REPORT_TOKEN
        )
    )
    if shared is None:
        shared = SharedReport(
            tenant_id=tenant.id,
            report_definition_id=report_def.id,
            public_token=_SHARED_REPORT_TOKEN,
            expires_at=None,
            is_active=True,
            view_count=0,
        )
        db.add(shared)
        db.flush()
        print(f"  Created SharedReport token={_SHARED_REPORT_TOKEN[:20]}... ({shared.id})")
        counts["shared_reports"] = 1
    else:
        print(f"  SharedReport already exists ({shared.id})")

    db.commit()
    return counts


# ── Main ──────────────────────────────────────────────────────────────────────


def run_seed() -> None:
    print("=" * 60)
    print("AYAZ Demo Seed Script  (enriched)")
    print("=" * 60)

    # Test DB connectivity
    try:
        with engine.connect() as conn:
            conn.execute(select(1))  # type: ignore[arg-type]
    except OperationalError as exc:
        print(f"\nERROR: Cannot connect to database.\n  {exc}")
        print(
            "\nTo run the seed you need a Postgres instance with the schema applied:\n"
            "  cd backend && alembic upgrade head\n"
            "  python -m scripts.seed_demo\n"
        )
        sys.exit(1)

    db = SessionLocal()

    summary: dict = {}

    try:
        # ── Step 1: Core OLTP ────────────────────────────────────────────────
        print("\n[1/7] Creating demo tenant, user, and membership...")
        tenant = _get_or_create_tenant(db)
        user = _get_or_create_user(db)
        _get_or_create_membership(db, user, tenant)
        db.commit()

        # ── Step 2: Connected accounts for all 3 rich channels ───────────────
        print("\n[2/7] Creating connected accounts (google_ads, meta_ads, tiktok_ads)...")
        channel_accounts: dict[str, ConnectedAccount] = {}
        for ch_spec in _CHANNEL_SPECS:
            acc = _get_or_create_connected_account(
                db, tenant,
                platform=ch_spec["platform"],
                external_id=ch_spec["account_ext_id"],
                display_name=ch_spec["account_display"],
            )
            channel_accounts[ch_spec["channel_key"]] = acc

        # Also create the legacy fixture accounts (sample + google_ads fixture)
        sample_account = _get_or_create_connected_account(
            db, tenant,
            platform=Platform.sample,
            external_id="ACC-001",
            display_name="Sample Ad Account (fixture)",
        )
        gads_fixture_account = _get_or_create_connected_account(
            db, tenant,
            platform=Platform.google_ads,
            external_id="1234567890",
            display_name="Google Ads Account (fixture)",
        )
        db.commit()

        # ── Step 3: Legacy fixture syncs (preserved from original seed) ──────
        print("\n[3/7] Syncing legacy 'sample' connector (fixture mode)...")
        sample_result = sync_connected_account(
            db,
            account=sample_account,
            since=_SYNC_SINCE,
            until=_SYNC_UNTIL,
        )
        print(
            f"  sample: inserted={sample_result['inserted']} "
            f"updated={sample_result['updated']} "
            f"records={sample_result['records_processed']}"
        )

        print("\n[4/7] Syncing legacy 'google_ads' connector (fixture mode)...")
        gads_config = ConnectorConfig(
            tenant_id=str(tenant.id),
            connected_account_id=str(gads_fixture_account.id),
            external_account_id=gads_fixture_account.external_account_id,
            platform_key="google_ads",
            vault_secret_ref="",
            extra={"customer_id": "1234567890", "currency": "USD"},
        )
        fixture_connector = _FixtureGoogleAdsConnector(
            config=gads_config,
            fixture_path=_GOOGLE_ADS_FIXTURE,
        )

        gads_fixture_account.sync_status = SyncStatus.syncing
        db.flush()

        caps = fixture_connector.capabilities()
        all_records = []
        for stream in caps.supported_streams:
            raw = fixture_connector.fetch(
                stream=stream, since=_SYNC_SINCE, until=_SYNC_UNTIL
            )
            all_records.extend(fixture_connector.normalize(raw))

        gads_channel = _get_or_create_channel(db, "google_ads")
        g_inserted = 0
        g_updated = 0
        for rec in all_records:
            _ensure_dim_date(db, rec.date_key)
            campaign = _get_or_create_campaign(
                db, tenant.id, gads_channel, rec.campaign_id, rec.campaign_name
            )
            adset = _get_or_create_adset(
                db, tenant.id, campaign, rec.adset_id, rec.adset_name
            )
            ad = _get_or_create_ad(
                db, tenant.id, adset, rec.ad_id, rec.ad_name
            )
            _, created = _upsert_fact(
                db,
                tenant_id=tenant.id,
                connected_account_id=gads_fixture_account.id,
                channel=gads_channel,
                campaign=campaign,
                adset=adset,
                ad=ad,
                record=rec,
            )
            if created:
                g_inserted += 1
            else:
                g_updated += 1

        if all_records:
            latest = max(r.date_key for r in all_records)
            gads_fixture_account.watermark = latest.isoformat()
        gads_fixture_account.sync_status = SyncStatus.success
        db.commit()
        print(
            f"  google_ads fixture: inserted={g_inserted} updated={g_updated} "
            f"records={len(all_records)}"
        )

        # ── Step 5: Rich 45-day fact data with anomalies ─────────────────────
        print("\n[5/7] Generating 45 days of rich FactDailyMetrics (3 channels, 7 campaigns)...")
        print(
            f"  Date range: {_RICH_START_DATE} — {_RICH_END_DATE}  "
            f"(anomaly window: {_RICH_START_DATE + timedelta(days=_ANOMALY_START_OFFSET)} — {_RICH_END_DATE})"
        )
        fact_inserted, fact_updated = _seed_rich_facts(db, tenant, channel_accounts)
        print(f"  Rich facts: inserted={fact_inserted}  updated={fact_updated}")
        total_facts = fact_inserted + fact_updated
        summary["fact_inserted"] = fact_inserted
        summary["fact_updated"] = fact_updated

        # ── Step 6: Feeds ─────────────────────────────────────────────────────
        print("\n[6/7] Seeding product feed (FeedSource + 2 FeedChannels + rules)...")
        feed_counts = _seed_feeds(db, tenant)
        summary["feeds"] = feed_counts
        print(
            f"  Feed sources={feed_counts['feed_sources']}  "
            f"products={feed_counts['products']}  "
            f"channels={feed_counts['channels']}  "
            f"rules={feed_counts['rules']}"
        )

        # ── Step 7: Insights ──────────────────────────────────────────────────
        print("\n[7/7] Generating insights (running all detectors)...")
        insight_counts = generate_insights(
            db,
            tenant_id=tenant.id,
            as_of_date=_RICH_END_DATE,
            lookback_days=45,
        )
        db.commit()
        summary["insights"] = insight_counts
        print(
            f"  Insights: new_info={insight_counts['new_info']}  "
            f"new_warning={insight_counts['new_warning']}  "
            f"new_critical={insight_counts['new_critical']}  "
            f"skipped={insight_counts['skipped']}"
        )

        # ── Optional: Reports ─────────────────────────────────────────────────
        print("\n[bonus] Seeding ReportDefinition + SharedReport...")
        report_counts = _seed_reports(db, tenant, user)
        summary["reports"] = report_counts

    finally:
        db.close()

    # ── Summary ───────────────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("Seed complete — full demo data summary")
    print("=" * 60)
    print()
    print("Fact rows (rich 45-day, 3 channels, 7 campaigns):")
    print(f"  Inserted : {summary.get('fact_inserted', 0)}")
    print(f"  Updated  : {summary.get('fact_updated', 0)}")
    print()
    print("Anomalies injected (last 7 days):")
    print("  google_ads / 'Brand Search'    — ROAS drop  (conv_value x 0.35)")
    print("  meta_ads   / 'Retargeting'     — Spend spike (cost x 3.2)")
    print("  tiktok_ads / 'Viral Creative'  — Zero conversions")
    print()
    feeds = summary.get("feeds", {})
    print("Product feeds:")
    print(f"  FeedSources : {feeds.get('feed_sources', 0) or '(already existed)'}")
    print(f"  Products    : {feeds.get('products', 0)}")
    print(f"  Channels    : {feeds.get('channels', 0) or '(already existed)'}")
    print(f"  Rules       : {feeds.get('rules', 0) or '(already existed)'}")
    print(f"  Google Shopping URL  : /api/v1/feeds/public/{_GOOGLE_FEED_TOKEN}")
    print(f"  Meta Catalog URL     : /api/v1/feeds/public/{_META_FEED_TOKEN}")
    print()
    ins = summary.get("insights", {})
    print("Insights generated:")
    print(f"  info={ins.get('new_info', 0)}  warning={ins.get('new_warning', 0)}  critical={ins.get('new_critical', 0)}  skipped={ins.get('skipped', 0)}")
    print()
    rpts = summary.get("reports", {})
    print("Reports:")
    print(f"  Definitions : {rpts.get('report_definitions', 0) or '(already existed)'}")
    print(f"  Shared link : /api/v1/reports/public/{_SHARED_REPORT_TOKEN}")
    print()
    print("Demo login credentials:")
    print(f"  Email    : {DEMO_EMAIL}")
    print(f"  Password : {DEMO_PASSWORD}")
    print()
    print("To obtain a JWT:")
    print(
        f'  curl -s -X POST http://localhost:8000/api/v1/auth/login \\\n'
        f'    -H "Content-Type: application/json" \\\n'
        f'    -d \'{{"email":"{DEMO_EMAIL}","password":"{DEMO_PASSWORD}"}}\''
    )
    print("=" * 60)


if __name__ == "__main__":
    run_seed()
