"""Demo seed script — populates the full AYAZ app with realistic demo data.

Usage
-----
From the ``backend/`` directory:

    python -m scripts.seed_demo          # as a module
    python scripts/seed_demo.py          # as a script

The script is fully idempotent: running it multiple times will not duplicate
data.  It creates:

1. A demo Tenant (name "AYAZ Demo", base_currency "TRY").
2. A demo User (email ``demo@ayaz.app``, password ``demo12345``).
3. An owner Membership linking the user to the tenant.
4. Three ConnectedAccounts: google_ads, meta_ads, tiktok_ads.
5. 45 days of FactDailyMetrics for 3 channels x 2-3 campaigns each, with
   realistic baselines, mild noise, and injected anomalies in the last 7 days:
     - google_ads / "Brand Search"   : ROAS drop in days -6 to -1  (critical)
     - meta_ads  / "Retargeting"     : spend spike in days -5 to -1 (warning)
     - tiktok_ads / "Viral Creative" : zero conversions in days -7 to -1
6. A FeedSource ("Demo Ürün Feed'i") with products from sample_feed.xml, plus
   two FeedChannels (google_shopping XML + meta_catalog CSV) each with rules.
7. Insights generated by calling services.insights.generate_insights.
8. One ReportDefinition (white-label) with a SharedReport link (if the reports
   model is importable — guarded with try/except for forward-compat).

Connector fixtures
------------------
``sample``    — ``tests/fixtures/sample_metrics.json`` (3 rows, 2024-03)
``google_ads`` — ``tests/fixtures/google_ads_search_stream.json`` (3 rows, 2024-06)

The GoogleAdsConnector is used in *fixture mode*: we directly call
``normalize()`` on the pre-recorded fixture rather than calling ``fetch()``
(which would hit the real API).  We do this by subclassing GoogleAdsConnector
and overriding ``fetch()`` to load the local fixture instead.

Anomaly injection
-----------------
All fact values are generated deterministically via index-based arithmetic
(no random seed needed — same index always produces the same value).
Anomalies are injected by overriding the computed value for specific
(channel, campaign, day-offset) combinations in the last 7 days:
  - ROAS drop: conversion_value_raw halved on google_ads "Brand Search"
  - Spend spike: cost_raw tripled on meta_ads "Retargeting"
  - Zero conversions: conversions forced to 0 on tiktok_ads "Viral Creative"

Exit codes
----------
0 — success
1 — DB unreachable (prints the error and instructions)
"""

from __future__ import annotations

import json
import secrets
import sys
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path

# Ensure the backend package root is on sys.path when run as a plain script.
_BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(_BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(_BACKEND_DIR))

from sqlalchemy import select
from sqlalchemy.exc import OperationalError

from ayaz.connectors.base import ConnectorConfig
from ayaz.connectors.google_ads import GoogleAdsConnector
from ayaz.connectors.sample import SampleConnector
from ayaz.database import SessionLocal, engine
from ayaz.models.analytics import (  # noqa: F401 — ensure tables known
    DimChannel,
    DimCampaign,
    DimAdSet,
    DimAd,
    DimDate,
    FactDailyMetrics,
)
from ayaz.models.base import Base
from ayaz.models.feeds import FeedChannel, FeedProduct, FeedRule, FeedSource
from ayaz.models.tracking import (
    ConversionEvent,
    EventDestination,
    TrackingSource,
)
from ayaz.models.content import ContentPost
from ayaz.models.budget import BudgetPlan
from ayaz.models.social_inbox import SocialMessage, SocialReply
from ayaz.models.oltp import (
    ConnectedAccount,
    Membership,
    MembershipRole,
    Platform,
    SyncStatus,
    Tenant,
    User,
)
from ayaz.services.auth import hash_password
from ayaz.services.feeds import ingest_feed_source
from ayaz.services.insights import generate_insights
from ayaz.services.tracking import compute_match_quality, hash_identity
from ayaz.services.sync import (
    _ensure_dim_date,
    _get_or_create_channel,
    _get_or_create_campaign,
    _get_or_create_adset,
    _get_or_create_ad,
    _upsert_fact,
    sync_connected_account,
)

# Reports model is guarded — may be absent in very early branches.
try:
    from ayaz.models.reports import ReportDefinition, SharedReport
    _REPORTS_AVAILABLE = True
except ImportError:
    _REPORTS_AVAILABLE = False

# ── Constants ─────────────────────────────────────────────────────────────────

DEMO_EMAIL = "demo@ayaz.app"
DEMO_PASSWORD = "demo12345"
DEMO_TENANT_NAME = "AYAZ Demo"
DEMO_CURRENCY = "TRY"

_FIXTURES_DIR = Path(__file__).resolve().parent.parent / "tests" / "fixtures"
_SAMPLE_FIXTURE = _FIXTURES_DIR / "sample_metrics.json"
_GOOGLE_ADS_FIXTURE = _FIXTURES_DIR / "google_ads_search_stream.json"
_FEED_FIXTURE = _FIXTURES_DIR / "sample_feed.xml"

# Date range for legacy fixture syncs (kept from original seed)
_SYNC_SINCE = date(2024, 1, 1)
_SYNC_UNTIL = date(2024, 12, 31)

# Rich fact data: 45 days ending 2026-06-25 (one day before today 2026-06-26)
_RICH_END_DATE = date(2026, 6, 25)
_RICH_START_DATE = _RICH_END_DATE - timedelta(days=44)  # 45 days inclusive
_ANOMALY_START_OFFSET = 38  # days from _RICH_START_DATE where anomalies begin (last 7 days)

# ── Channel / campaign definitions ────────────────────────────────────────────

# Each entry: (channel_key, platform_enum, account_external_id, account_display_name,
#              list of (campaign_ext_id, campaign_name, adset_ext_id, adset_name,
#                       ad_ext_id, ad_name,
#                       base_impressions, base_clicks, base_cost_try, base_conv, base_conv_val))
_CHANNEL_SPECS = [
    {
        "channel_key": "google_ads",
        "platform": Platform.google_ads,
        "account_ext_id": "GADS-DEMO-001",
        "account_display": "Google Ads — Demo Hesap",
        "cost_ccy": "TRY",
        "campaigns": [
            {
                "camp_ext": "G-CAMP-BRAND",
                "camp_name": "Brand Search",
                "adset_ext": "G-AS-BRAND-EXACT",
                "adset_name": "Marka Exact Match",
                "ad_ext": "G-AD-BRAND-RSA",
                "ad_name": "Marka RSA v1",
                # baselines per day
                "impressions": 12000,
                "clicks": 480,
                "cost": Decimal("1200.00"),
                "conversions": Decimal("24.0"),
                "conv_value": Decimal("6000.00"),
                # anomaly: ROAS drop — halve conv_value in last 7 days
                "anomaly": "roas_drop",
            },
            {
                "camp_ext": "G-CAMP-PRSP",
                "camp_name": "Prospecting — Genis Kitle",
                "adset_ext": "G-AS-PRSP-INT",
                "adset_name": "Ilgi Alanlari",
                "ad_ext": "G-AD-PRSP-DSA",
                "ad_name": "DSA Koleksiyon",
                "impressions": 45000,
                "clicks": 900,
                "cost": Decimal("2250.00"),
                "conversions": Decimal("18.0"),
                "conv_value": Decimal("5400.00"),
                "anomaly": None,
            },
            {
                "camp_ext": "G-CAMP-SHOP",
                "camp_name": "Shopping — Urun Listesi",
                "adset_ext": "G-AS-SHOP-ALL",
                "adset_name": "Tum Urunler",
                "ad_ext": "G-AD-SHOP-DYNA",
                "ad_name": "Dinamik Shopping",
                "impressions": 30000,
                "clicks": 600,
                "cost": Decimal("1800.00"),
                "conversions": Decimal("30.0"),
                "conv_value": Decimal("9000.00"),
                "anomaly": None,
            },
        ],
    },
    {
        "channel_key": "meta_ads",
        "platform": Platform.meta_ads,
        "account_ext_id": "META-DEMO-001",
        "account_display": "Meta Ads — Demo Hesap",
        "cost_ccy": "TRY",
        "campaigns": [
            {
                "camp_ext": "M-CAMP-RETG",
                "camp_name": "Retargeting — Sepet Terk",
                "adset_ext": "M-AS-RETG-7D",
                "adset_name": "7 Gunluk Ziyaretci",
                "ad_ext": "M-AD-RETG-CARO",
                "ad_name": "Carousel — Sepet Urunu",
                "impressions": 25000,
                "clicks": 750,
                "cost": Decimal("1875.00"),
                "conversions": Decimal("37.0"),
                "conv_value": Decimal("11100.00"),
                # anomaly: spend spike in last 7 days
                "anomaly": "spend_spike",
            },
            {
                "camp_ext": "M-CAMP-ACQST",
                "camp_name": "Musteri Kazanimi — LAL",
                "adset_ext": "M-AS-LAL-2PCT",
                "adset_name": "2pct Lookalike",
                "ad_ext": "M-AD-LAL-VID",
                "ad_name": "Video — Marka Hikayesi",
                "impressions": 60000,
                "clicks": 900,
                "cost": Decimal("2700.00"),
                "conversions": Decimal("27.0"),
                "conv_value": Decimal("8100.00"),
                "anomaly": None,
            },
        ],
    },
    {
        "channel_key": "tiktok_ads",
        "platform": Platform.tiktok_ads,
        "account_ext_id": "TTADS-DEMO-001",
        "account_display": "TikTok Ads — Demo Hesap",
        "cost_ccy": "TRY",
        "campaigns": [
            {
                "camp_ext": "TT-CAMP-VIRAL",
                "camp_name": "Viral Creative — Gen Z",
                "adset_ext": "TT-AS-VIRAL-18-24",
                "adset_name": "18-24 Yas",
                "ad_ext": "TT-AD-VIRAL-UGC",
                "ad_name": "UGC Video — Dans Challenge",
                "impressions": 80000,
                "clicks": 1600,
                "cost": Decimal("2000.00"),
                "conversions": Decimal("20.0"),
                "conv_value": Decimal("5000.00"),
                # anomaly: zero conversions in last 7 days
                "anomaly": "zero_conversions",
            },
            {
                "camp_ext": "TT-CAMP-SPARK",
                "camp_name": "Spark Ads — Influencer",
                "adset_ext": "TT-AS-SPARK-MID",
                "adset_name": "Mid-tier Influencer",
                "ad_ext": "TT-AD-SPARK-HAUL",
                "ad_name": "Haul Video — Moda",
                "impressions": 50000,
                "clicks": 1000,
                "cost": Decimal("1500.00"),
                "conversions": Decimal("15.0"),
                "conv_value": Decimal("3750.00"),
                "anomaly": None,
            },
        ],
    },
]


# ── Noise helper (deterministic, index-based) ──────────────────────────────────

def _noise(base: Decimal, day_index: int, campaign_index: int, scale: float = 0.12) -> Decimal:
    """Return a deterministic pseudo-noise perturbation around ``base``.

    Uses a repeating pattern derived from the day and campaign index —
    no random module, so results are identical on every run.

    Pattern: a 7-step sawtooth combined with a 11-step offset, giving a
    17-step cycle (coprime pair) that looks organic in a chart without
    needing a random seed.
    """
    # 7-step sawtooth: -3, -2, -1, 0, +1, +2, +3 (repeats)
    saw7 = ((day_index + campaign_index * 3) % 7) - 3   # range [-3, 3]
    # 11-step second wave
    saw11 = ((day_index * 2 + campaign_index) % 11) - 5  # range [-5, 5]
    # Normalise: combined range is -8..8, scale to [-scale, +scale]
    factor = Decimal(str((saw7 + saw11) / 8.0 * scale))
    return base * (Decimal("1") + factor)


# ── Fixture-backed GoogleAds connector ────────────────────────────────────────


class _FixtureGoogleAdsConnector(GoogleAdsConnector):
    """GoogleAdsConnector with fetch() replaced by fixture loading.

    Used by the seed script only — never registers itself in the ConnectorRegistry
    because ``platform_key`` is cleared at the class level so ``__init_subclass__``
    skips registration (only subclasses that define platform_key as a non-empty
    string are registered).
    No live network calls are made.
    """

    # Clear platform_key so __init_subclass__ skips registration
    platform_key = ""  # type: ignore[assignment]

    def __init__(self, config: ConnectorConfig, fixture_path: Path) -> None:
        super().__init__(config)
        self._fixture_path = fixture_path
        # Provide a dummy access token so _auth_headers() won't raise
        self._access_token = "fixture-mode-no-token"

    def fetch(self, stream: str, since: date, until: date):  # type: ignore[override]
        """Load the recorded fixture and return the flattened row list."""
        with self._fixture_path.open(encoding="utf-8") as fh:
            raw_body = json.load(fh)
        rows = self._parse_stream_response(raw_body)
        # Filter by date range
        filtered = [
            r for r in rows
            if since <= date.fromisoformat(r["segments"]["date"]) <= until
        ]
        return filtered

    def authenticate(self) -> None:  # type: ignore[override]
        """No-op in fixture mode."""

    def refresh_token(self) -> None:  # type: ignore[override]
        """No-op in fixture mode."""


# ── OLTP helpers ──────────────────────────────────────────────────────────────


def _get_or_create_tenant(db) -> Tenant:
    tenant = db.scalar(select(Tenant).where(Tenant.name == DEMO_TENANT_NAME))
    if tenant is None:
        tenant = Tenant(
            name=DEMO_TENANT_NAME,
            base_currency=DEMO_CURRENCY,
            country="TR",
            kvkk_region="TR",
        )
        db.add(tenant)
        db.flush()
        print(f"  Created tenant: {DEMO_TENANT_NAME} ({tenant.id})")
    else:
        print(f"  Tenant already exists: {DEMO_TENANT_NAME} ({tenant.id})")
    return tenant


def _get_or_create_user(db) -> User:
    user = db.scalar(select(User).where(User.email == DEMO_EMAIL))
    if user is None:
        user = User(
            email=DEMO_EMAIL,
            hashed_password=hash_password(DEMO_PASSWORD),
            full_name="AYAZ Demo User",
        )
        db.add(user)
        db.flush()
        print(f"  Created user: {DEMO_EMAIL} ({user.id})")
    else:
        print(f"  User already exists: {DEMO_EMAIL} ({user.id})")
    return user


def _get_or_create_membership(db, user: User, tenant: Tenant) -> Membership:
    membership = db.scalar(
        select(Membership).where(
            Membership.user_id == user.id,
            Membership.tenant_id == tenant.id,
        )
    )
    if membership is None:
        membership = Membership(
            user_id=user.id,
            tenant_id=tenant.id,
            role=MembershipRole.owner,
        )
        db.add(membership)
        db.flush()
        print("  Created owner membership")
    else:
        print("  Membership already exists")
    return membership


def _get_or_create_connected_account(
    db,
    tenant: Tenant,
    platform: Platform,
    external_id: str,
    display_name: str,
) -> ConnectedAccount:
    account = db.scalar(
        select(ConnectedAccount).where(
            ConnectedAccount.tenant_id == tenant.id,
            ConnectedAccount.platform == platform,
            ConnectedAccount.external_account_id == external_id,
        )
    )
    if account is None:
        account = ConnectedAccount(
            tenant_id=tenant.id,
            platform=platform,
            external_account_id=external_id,
            display_name=display_name,
            vault_secret_ref="",
            sync_status=SyncStatus.idle,
        )
        db.add(account)
        db.flush()
        print(f"  Created ConnectedAccount: {platform.value} / {external_id}")
    else:
        print(f"  ConnectedAccount already exists: {platform.value} / {external_id}")
    return account


# ── Rich fact data generation ─────────────────────────────────────────────────


def _seed_rich_facts(db, tenant: Tenant, accounts: dict[str, ConnectedAccount]) -> tuple[int, int]:
    """Generate 45 days of FactDailyMetrics across 3 channels with anomalies.

    Returns (inserted, updated) counts.
    """
    inserted = 0
    updated = 0
    now_utc = datetime.now(timezone.utc)

    date_range = [
        _RICH_START_DATE + timedelta(days=d)
        for d in range(45)
    ]

    for ch_idx, ch_spec in enumerate(_CHANNEL_SPECS):
        channel_key = ch_spec["channel_key"]
        channel = _get_or_create_channel(db, channel_key)
        account = accounts[channel_key]

        for camp_idx, camp in enumerate(ch_spec["campaigns"]):
            campaign = _get_or_create_campaign(
                db, tenant.id, channel,
                external_id=camp["camp_ext"],
                name=camp["camp_name"],
            )
            adset = _get_or_create_adset(
                db, tenant.id, campaign,
                external_id=camp["adset_ext"],
                name=camp["adset_name"],
            )
            ad = _get_or_create_ad(
                db, tenant.id, adset,
                external_id=camp["ad_ext"],
                name=camp["ad_name"],
            )

            for day_idx, d in enumerate(date_range):
                _ensure_dim_date(db, d)

                # Base values with deterministic noise
                impressions = int(_noise(Decimal(camp["impressions"]), day_idx, camp_idx))
                clicks = max(1, int(_noise(Decimal(camp["clicks"]), day_idx, camp_idx + 1)))
                cost = _noise(camp["cost"], day_idx, camp_idx + 2).quantize(Decimal("0.01"))
                conversions = _noise(camp["conversions"], day_idx, camp_idx + 3).quantize(Decimal("0.01"))
                conv_value = _noise(camp["conv_value"], day_idx, camp_idx + 4).quantize(Decimal("0.01"))

                # Clamp to reasonable minimums
                clicks = min(clicks, impressions)
                cost = max(Decimal("0.01"), cost)
                conversions = max(Decimal("0"), conversions)
                conv_value = max(Decimal("0"), conv_value)

                # ── Anomaly injection (last 7 days = day_idx >= _ANOMALY_START_OFFSET) ──
                in_anomaly_window = day_idx >= _ANOMALY_START_OFFSET

                if in_anomaly_window and camp.get("anomaly") == "roas_drop":
                    # ROAS drop on google_ads Brand Search: halve conversion value
                    conv_value = (conv_value * Decimal("0.35")).quantize(Decimal("0.01"))

                elif in_anomaly_window and camp.get("anomaly") == "spend_spike":
                    # Spend spike on meta_ads Retargeting: triple cost
                    cost = (cost * Decimal("3.2")).quantize(Decimal("0.01"))

                elif in_anomaly_window and camp.get("anomaly") == "zero_conversions":
                    # Zero conversions on tiktok_ads Viral Creative: conversions → 0
                    conversions = Decimal("0")
                    conv_value = Decimal("0")

                # Check if fact row already exists for this grain
                existing = db.scalar(
                    select(FactDailyMetrics).where(
                        FactDailyMetrics.tenant_id == tenant.id,
                        FactDailyMetrics.connected_account_id == account.id,
                        FactDailyMetrics.channel_id == channel.id,
                        FactDailyMetrics.campaign_id == campaign.id,
                        FactDailyMetrics.adset_id == adset.id,
                        FactDailyMetrics.ad_id == ad.id,
                        FactDailyMetrics.date_key == d,
                    )
                )

                if existing is None:
                    fact = FactDailyMetrics(
                        tenant_id=tenant.id,
                        connected_account_id=account.id,
                        channel_id=channel.id,
                        campaign_id=campaign.id,
                        adset_id=adset.id,
                        ad_id=ad.id,
                        date_key=d,
                        impressions=impressions,
                        clicks=clicks,
                        cost_raw=cost,
                        cost_ccy=ch_spec["cost_ccy"],
                        conversions=conversions,
                        conversion_value_raw=conv_value,
                        conversion_value_ccy=ch_spec["cost_ccy"],
                        # Placeholder: no FX conversion — base_ccy = raw
                        cost_base_ccy=cost,
                        conv_value_base_ccy=conv_value,
                        ingested_at=now_utc,
                    )
                    db.add(fact)
                    inserted += 1
                else:
                    existing.impressions = impressions
                    existing.clicks = clicks
                    existing.cost_raw = cost
                    existing.cost_ccy = ch_spec["cost_ccy"]
                    existing.conversions = conversions
                    existing.conversion_value_raw = conv_value
                    existing.conversion_value_ccy = ch_spec["cost_ccy"]
                    existing.cost_base_ccy = cost
                    existing.conv_value_base_ccy = conv_value
                    existing.ingested_at = now_utc
                    updated += 1

        # Flush per channel to keep memory bounded
        db.flush()

    db.commit()
    return inserted, updated


# ── Ad-level creative fact data ───────────────────────────────────────────────

# Additional ads per campaign: 3 extra ads per campaign for the recent 14-day
# window, alongside the existing per-campaign ad already created by _seed_rich_facts.
# Performance intentionally varied so creatives analysis has clear winners/losers.
#
# Each entry:
#   (ad_ext_id, ad_name, impressions_fraction, clicks_fraction,
#    cost_fraction, conv_fraction, conv_value_fraction)
# Fractions are relative to the parent campaign's base values.
#
# Campaigns chosen: one per channel (first campaign of each) so the demo surface
# is representative without over-inflating the fact table.

_AD_LEVEL_SPECS = [
    # ── google_ads / Brand Search ──────────────────────────────────────────
    {
        "channel_key": "google_ads",
        "camp_ext": "G-CAMP-BRAND",
        "cost_ccy": "TRY",
        "extra_ads": [
            {
                "ad_ext": "G-AD-BRAND-VID",
                "ad_name": "Video — Indirim Kampanyasi",
                # High ROAS winner: good conversions relative to spend
                "imp_frac": Decimal("0.35"),
                "clk_frac": Decimal("0.40"),
                "cost_frac": Decimal("0.30"),
                "conv_frac": Decimal("0.55"),   # strong performer
                "cv_frac":   Decimal("0.60"),
            },
            {
                "ad_ext": "G-AD-BRAND-STAT",
                "ad_name": "Statik — Marka Gorseli",
                # Moderate performer
                "imp_frac": Decimal("0.30"),
                "clk_frac": Decimal("0.28"),
                "cost_frac": Decimal("0.28"),
                "conv_frac": Decimal("0.25"),
                "cv_frac":   Decimal("0.24"),
            },
            {
                "ad_ext": "G-AD-BRAND-RESP",
                "ad_name": "Responsive — Sezon Teklifi",
                # Budget waster: spends but very few conversions
                "imp_frac": Decimal("0.25"),
                "clk_frac": Decimal("0.20"),
                "cost_frac": Decimal("0.32"),   # over-spending
                "conv_frac": Decimal("0.04"),   # near-zero conversions
                "cv_frac":   Decimal("0.03"),
            },
        ],
    },
    # ── meta_ads / Retargeting — Sepet Terk ───────────────────────────────
    {
        "channel_key": "meta_ads",
        "camp_ext": "M-CAMP-RETG",
        "cost_ccy": "TRY",
        "extra_ads": [
            {
                "ad_ext": "M-AD-RETG-VID",
                "ad_name": "Video — Sepet Hatirlatma",
                # High ROAS winner for meta
                "imp_frac": Decimal("0.40"),
                "clk_frac": Decimal("0.45"),
                "cost_frac": Decimal("0.35"),
                "conv_frac": Decimal("0.50"),
                "cv_frac":   Decimal("0.55"),
            },
            {
                "ad_ext": "M-AD-RETG-STAT",
                "ad_name": "Statik — Indirim Afisi",
                # Moderate
                "imp_frac": Decimal("0.30"),
                "clk_frac": Decimal("0.28"),
                "cost_frac": Decimal("0.28"),
                "conv_frac": Decimal("0.28"),
                "cv_frac":   Decimal("0.26"),
            },
            {
                "ad_ext": "M-AD-RETG-COLL",
                "ad_name": "Koleksiyon — Tum Koleksiyon",
                # Loser: spend but zero conversions
                "imp_frac": Decimal("0.20"),
                "clk_frac": Decimal("0.18"),
                "cost_frac": Decimal("0.28"),   # meaningful spend
                "conv_frac": Decimal("0.00"),   # zero conversions (budget waster)
                "cv_frac":   Decimal("0.00"),
            },
        ],
    },
    # ── tiktok_ads / Viral Creative — Gen Z ───────────────────────────────
    {
        "channel_key": "tiktok_ads",
        "camp_ext": "TT-CAMP-VIRAL",
        "cost_ccy": "TRY",
        "extra_ads": [
            {
                "ad_ext": "TT-AD-VIRAL-DUO",
                "ad_name": "Duet — Urun Tanitim",
                # Strong performer
                "imp_frac": Decimal("0.38"),
                "clk_frac": Decimal("0.40"),
                "cost_frac": Decimal("0.30"),
                "conv_frac": Decimal("0.50"),
                "cv_frac":   Decimal("0.52"),
            },
            {
                "ad_ext": "TT-AD-VIRAL-STC",
                "ad_name": "Statik — Flash Indirim",
                # Moderate
                "imp_frac": Decimal("0.28"),
                "clk_frac": Decimal("0.25"),
                "cost_frac": Decimal("0.25"),
                "conv_frac": Decimal("0.22"),
                "cv_frac":   Decimal("0.20"),
            },
            {
                "ad_ext": "TT-AD-VIRAL-WAS",
                "ad_name": "Spark — Dusuk Performans",
                # Worst: spend, near-zero conversions
                "imp_frac": Decimal("0.24"),
                "clk_frac": Decimal("0.20"),
                "cost_frac": Decimal("0.35"),
                "conv_frac": Decimal("0.02"),
                "cv_frac":   Decimal("0.02"),
            },
        ],
    },
]

# Recent window for ad-level fact rows: last 14 days of the rich window.
_AD_LEVEL_START = _RICH_END_DATE - timedelta(days=13)  # 14 days inclusive
_AD_LEVEL_END = _RICH_END_DATE


def _seed_ad_level_facts(
    db,
    tenant: Tenant,
    accounts: dict[str, ConnectedAccount],
) -> tuple[int, int]:
    """Seed ad-level FactDailyMetrics for the recent 14-day window.

    Creates 3 extra DimAd rows per selected campaign (1 per channel) and writes
    14 days of fact data with varied performance profiles:
      - High-ROAS winner ads
      - Moderate performers
      - Budget-wasting losers (spending but near/zero conversions)

    Uses get-or-create for dim rows and upserts facts on the 7-field grain.
    Returns (inserted, updated) counts.

    This data is additive — the existing campaign-level rows (from _seed_rich_facts)
    are not touched.
    """
    inserted = 0
    updated = 0
    now_utc = datetime.now(timezone.utc)

    date_range = [
        _AD_LEVEL_START + timedelta(days=d)
        for d in range(14)
    ]

    for spec in _AD_LEVEL_SPECS:
        channel_key = spec["channel_key"]
        cost_ccy = spec["cost_ccy"]
        channel = _get_or_create_channel(db, channel_key)
        account = accounts[channel_key]

        # Look up the parent campaign
        from sqlalchemy import select as _select
        from ayaz.models.analytics import DimCampaign as _DimCampaign
        campaign = db.scalar(
            _select(_DimCampaign).where(
                _DimCampaign.tenant_id == tenant.id,
                _DimCampaign.external_id == spec["camp_ext"],
            )
        )
        if campaign is None:
            print(
                f"  WARNING: campaign {spec['camp_ext']} not found "
                f"— ad-level seed skipped for this campaign"
            )
            continue

        # Find the adset already created for this campaign (first one)
        from ayaz.models.analytics import DimAdSet as _DimAdSet
        adset = db.scalar(
            _select(_DimAdSet).where(
                _DimAdSet.campaign_id == campaign.id,
                _DimAdSet.tenant_id == tenant.id,
            )
        )
        if adset is None:
            print(f"  WARNING: no adset found for campaign {spec['camp_ext']} — skipping")
            continue

        # Base values come from the campaign spec we already defined in _CHANNEL_SPECS
        # Re-derive by matching camp_ext in _CHANNEL_SPECS
        base_camp = None
        for ch_spec in _CHANNEL_SPECS:
            if ch_spec["channel_key"] == channel_key:
                for c in ch_spec["campaigns"]:
                    if c["camp_ext"] == spec["camp_ext"]:
                        base_camp = c
                        break
        if base_camp is None:
            print(f"  WARNING: base campaign spec not found for {spec['camp_ext']}")
            continue

        for ad_idx, ad_spec in enumerate(spec["extra_ads"]):
            ad = _get_or_create_ad(
                db, tenant.id, adset,
                external_id=ad_spec["ad_ext"],
                name=ad_spec["ad_name"],
            )

            for day_idx, d in enumerate(date_range):
                _ensure_dim_date(db, d)

                # Scale base campaign metrics by per-ad fractions with noise
                base_imp = Decimal(str(base_camp["impressions"])) * ad_spec["imp_frac"]
                base_clk = Decimal(str(base_camp["clicks"])) * ad_spec["clk_frac"]
                base_cost = base_camp["cost"] * ad_spec["cost_frac"]
                base_conv = base_camp["conversions"] * ad_spec["conv_frac"]
                base_cv = base_camp["conv_value"] * ad_spec["cv_frac"]

                # Apply deterministic noise (slightly different seed per ad_idx)
                impressions = max(1, int(_noise(base_imp, day_idx, ad_idx + 10)))
                clicks = max(1, int(_noise(base_clk, day_idx, ad_idx + 11)))
                cost = _noise(base_cost, day_idx, ad_idx + 12).quantize(Decimal("0.01"))
                conversions = _noise(base_conv, day_idx, ad_idx + 13).quantize(Decimal("0.01"))
                conv_value = _noise(base_cv, day_idx, ad_idx + 14).quantize(Decimal("0.01"))

                # Clamp
                clicks = min(clicks, impressions)
                cost = max(Decimal("0.01"), cost)
                conversions = max(Decimal("0"), conversions)
                conv_value = max(Decimal("0"), conv_value)

                # Hard-zero for designated waster ads (conv_frac == 0)
                if ad_spec["conv_frac"] == Decimal("0.00"):
                    conversions = Decimal("0")
                    conv_value = Decimal("0")

                # Upsert on the 7-field grain
                existing = db.scalar(
                    select(FactDailyMetrics).where(
                        FactDailyMetrics.tenant_id == tenant.id,
                        FactDailyMetrics.connected_account_id == account.id,
                        FactDailyMetrics.channel_id == channel.id,
                        FactDailyMetrics.campaign_id == campaign.id,
                        FactDailyMetrics.adset_id == adset.id,
                        FactDailyMetrics.ad_id == ad.id,
                        FactDailyMetrics.date_key == d,
                    )
                )

                if existing is None:
                    fact = FactDailyMetrics(
                        tenant_id=tenant.id,
                        connected_account_id=account.id,
                        channel_id=channel.id,
                        campaign_id=campaign.id,
                        adset_id=adset.id,
                        ad_id=ad.id,
                        date_key=d,
                        impressions=impressions,
                        clicks=clicks,
                        cost_raw=cost,
                        cost_ccy=cost_ccy,
                        conversions=conversions,
                        conversion_value_raw=conv_value,
                        conversion_value_ccy=cost_ccy,
                        cost_base_ccy=cost,
                        conv_value_base_ccy=conv_value,
                        ingested_at=now_utc,
                    )
                    db.add(fact)
                    inserted += 1
                else:
                    existing.impressions = impressions
                    existing.clicks = clicks
                    existing.cost_raw = cost
                    existing.cost_ccy = cost_ccy
                    existing.conversions = conversions
                    existing.conversion_value_raw = conv_value
                    existing.conversion_value_ccy = cost_ccy
                    existing.cost_base_ccy = cost
                    existing.conv_value_base_ccy = conv_value
                    existing.ingested_at = now_utc
                    updated += 1

        db.flush()

    db.commit()
    return inserted, updated


# ── Feed seeding ───────────────────────────────────────────────────────────────

# Stable tokens derived from a fixed prefix so they survive re-runs.
# (Not cryptographically random by design — they're just demo public URLs.)
_GOOGLE_FEED_TOKEN = "ayaz-demo-gshop-token-0000000001"
_META_FEED_TOKEN   = "ayaz-demo-meta-token-00000000001"


def _seed_feeds(db, tenant: Tenant) -> dict:
    """Create FeedSource, ingest products, and set up two FeedChannels with rules.

    Returns dict with counts.
    """
    counts = {"feed_sources": 0, "products": 0, "channels": 0, "rules": 0}

    # ── FeedSource ─────────────────────────────────────────────────────────
    feed_source = db.scalar(
        select(FeedSource).where(
            FeedSource.tenant_id == tenant.id,
            FeedSource.name == "Demo Urun Feed'i",
        )
    )
    if feed_source is None:
        feed_source = FeedSource(
            tenant_id=tenant.id,
            name="Demo Urun Feed'i",
            source_type="upload",
            source_url=None,
            status="pending",
            item_count=0,
        )
        db.add(feed_source)
        db.flush()
        print(f"  Created FeedSource: Demo Urun Feed'i ({feed_source.id})")
        counts["feed_sources"] = 1
    else:
        print(f"  FeedSource already exists: Demo Urun Feed'i ({feed_source.id})")

    # ── Ingest products from fixture XML ───────────────────────────────────
    if _FEED_FIXTURE.exists():
        raw_bytes = _FEED_FIXTURE.read_bytes()
        n_products = ingest_feed_source(db, feed_source, raw_bytes=raw_bytes)
        counts["products"] = n_products
        print(f"  Ingested {n_products} products from sample_feed.xml")
    else:
        print(f"  WARNING: fixture not found at {_FEED_FIXTURE} — skipping product ingest")

    # ── FeedChannel: Google Shopping XML ───────────────────────────────────
    gshop_channel = db.scalar(
        select(FeedChannel).where(
            FeedChannel.public_token == _GOOGLE_FEED_TOKEN
        )
    )
    if gshop_channel is None:
        gshop_channel = FeedChannel(
            tenant_id=tenant.id,
            feed_source_id=feed_source.id,
            name="Google Shopping — Tum Urunler",
            channel_type="google_shopping",
            output_format="xml",
            public_token=_GOOGLE_FEED_TOKEN,
            is_active=True,
        )
        db.add(gshop_channel)
        db.flush()
        print(f"  Created FeedChannel: google_shopping ({gshop_channel.id})")
        counts["channels"] += 1

        # Rule 1: filter out-of-stock products
        r1 = FeedRule(
            tenant_id=tenant.id,
            feed_channel_id=gshop_channel.id,
            position=1,
            rule_type="filter_include",
            config={
                "condition_field": "availability",
                "condition_op": "eq",
                "condition_value": "in stock",
            },
        )
        # Rule 2: append brand suffix to title
        r2 = FeedRule(
            tenant_id=tenant.id,
            feed_channel_id=gshop_channel.id,
            position=2,
            rule_type="calculated",
            config={
                "field": "title",
                "expression": "{title} | AYAZ Demo",
            },
        )
        db.add_all([r1, r2])
        db.flush()
        counts["rules"] += 2
    else:
        print(f"  FeedChannel google_shopping already exists ({gshop_channel.id})")

    # ── FeedChannel: Meta Catalog CSV ──────────────────────────────────────
    meta_channel = db.scalar(
        select(FeedChannel).where(
            FeedChannel.public_token == _META_FEED_TOKEN
        )
    )
    if meta_channel is None:
        meta_channel = FeedChannel(
            tenant_id=tenant.id,
            feed_source_id=feed_source.id,
            name="Meta Katalog — Aktif Urunler",
            channel_type="meta_catalog",
            output_format="csv",
            public_token=_META_FEED_TOKEN,
            is_active=True,
        )
        db.add(meta_channel)
        db.flush()
        print(f"  Created FeedChannel: meta_catalog ({meta_channel.id})")
        counts["channels"] += 1

        # Rule 1: force condition to "new" for Meta compliance
        r3 = FeedRule(
            tenant_id=tenant.id,
            feed_channel_id=meta_channel.id,
            position=1,
            rule_type="set_value",
            config={"field": "condition", "value": "new"},
        )
        # Rule 2: strip price unit suffix (Meta expects "149.99 USD" — already correct)
        r4 = FeedRule(
            tenant_id=tenant.id,
            feed_channel_id=meta_channel.id,
            position=2,
            rule_type="find_replace",
            config={
                "field": "price",
                "pattern": r"\s+USD$",
                "replacement": " USD",
                "use_regex": True,
            },
        )
        db.add_all([r3, r4])
        db.flush()
        counts["rules"] += 2
    else:
        print(f"  FeedChannel meta_catalog already exists ({meta_channel.id})")

    db.commit()
    return counts


# ── Tracking (M7) seeding ─────────────────────────────────────────────────────

# Stable token — deterministic so re-runs stay idempotent and the snippet
# embed URL never changes across seed invocations.
_TRACKING_SOURCE_NAME = "EasyCep Web"
_TRACKING_PUBLIC_TOKEN = "ayaz-demo-tracking-token-0000000001"

# Event distribution across the last 14 days.
# Index-based, fully deterministic — no random module used.
_TRACKING_EVENT_NAMES = [
    "PageView",        # index % 5 == 0,1,2  → most frequent
    "ViewContent",     # index % 5 == 3
    "AddToCart",       # index % 10 == 4
    "InitiateCheckout",# index % 10 == 7
    "Purchase",        # index % 20 == 9
]

# Map a 0-based event index to (event_name, status, consent, forwarded_count, error)
def _event_profile(idx: int):
    """Return deterministic (event_name, status, consent, forwarded_count, error)
    for a given 0-based event index.

    Distribution (100 events target):
      - event_name: PageView dominant (~40%), then ViewContent (~20%),
                    AddToCart (~20%), InitiateCheckout (~10%), Purchase (~10%).
      - status:
          forwarded        — ~60 events (idx % 10 in {0,1,2,3,5,6})
          skipped_no_consent — ~20 events (idx % 10 in {4,8}, consent=False)
          failed           — ~10 events (idx % 10 == 7)
          duplicate        — ~7 events  (idx % 15 == 14)
          received         — ~3 events  (idx % 30 == 29)
    """
    # event_name: 7-step cycle giving roughly the right distribution
    name_idx = (idx * 3 + idx // 7) % 10
    if name_idx <= 3:
        event_name = "PageView"
    elif name_idx <= 5:
        event_name = "ViewContent"
    elif name_idx <= 7:
        event_name = "AddToCart"
    elif name_idx == 8:
        event_name = "InitiateCheckout"
    else:
        event_name = "Purchase"

    # Override to ensure Purchase events are never skipped or failed
    # (they must be forwarded or duplicate for realistic data)
    if event_name == "Purchase" and (idx % 10 in {4, 7, 8}):
        event_name = "AddToCart"

    # status
    if idx % 15 == 14:
        status = "duplicate"
        consent = True
        forwarded_count = 0
        error = None
    elif idx % 30 == 29:
        status = "received"
        consent = True
        forwarded_count = 0
        error = None
    elif idx % 10 == 7:
        status = "failed"
        consent = True
        forwarded_count = 0
        # Deterministic error messages
        _errors = [
            "[meta_capi] HTTP 400: Invalid pixel_id",
            "[ga4_mp] HTTP 500: Internal Server Error",
            "[meta_capi] HTTP 403: Access token expired",
            "[ga4_mp] HTTP 429: Rate limit exceeded",
        ]
        error = _errors[idx % len(_errors)]
    elif idx % 10 in {4, 8}:
        status = "skipped_no_consent"
        consent = False
        forwarded_count = 0
        error = None
    else:
        status = "forwarded"
        consent = True
        # forwarded_count: 1 or 2 depending on which destinations matched consent
        forwarded_count = 2 if idx % 3 != 0 else 1
        error = None

    return event_name, status, consent, forwarded_count, error


def _identity_profile(event_name: str, idx: int) -> dict:
    """Return a deterministic RAW (pre-hash) user_data dict for a demo event.

    Identity completeness is correlated with intent: high-value events
    (Purchase / InitiateCheckout) carry richer signals than PageViews.  This
    produces a realistic spread of Match-Quality tiers and per-field coverage
    in the dashboard.  No real PII — emails use the reserved .invalid TLD.
    """
    user_num = idx % 20
    em = f"demouser{user_num:02d}@example.invalid"
    ph = f"+9053300{user_num:05d}"
    fbc = f"fb.1.{1700000000 + idx}.IwAR{idx:06d}"
    fbp = f"fb.1.{1700000000 + idx}.{(idx * 7) % 999999}"
    ext = f"easycep-cust-{user_num:04d}"
    ip = f"85.10.{idx % 255}.{(idx * 7) % 255}"
    ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"

    if event_name in ("Purchase", "InitiateCheckout"):
        bucket = idx % 4
        if bucket == 0:
            return {"email": em, "phone": ph, "fbc": fbc, "fbp": fbp,
                    "external_id": ext, "client_ip_address": ip,
                    "client_user_agent": ua}
        if bucket == 1:
            return {"email": em, "phone": ph, "fbp": fbp, "external_id": ext}
        if bucket == 2:
            return {"email": em, "phone": ph, "fbc": fbc,
                    "client_ip_address": ip, "client_user_agent": ua}
        return {"email": em, "phone": ph, "fbp": fbp}

    if event_name in ("AddToCart", "ViewContent"):
        bucket = idx % 3
        if bucket == 0:
            return {"email": em, "fbp": fbp, "client_ip_address": ip,
                    "client_user_agent": ua}
        if bucket == 1:
            return {"email": em, "fbp": fbp}
        return {"fbp": fbp, "client_ip_address": ip, "client_user_agent": ua}

    # PageView — poorest identity coverage
    if idx % 2 == 0:
        return {"client_ip_address": ip, "client_user_agent": ua}
    return {"fbp": fbp, "client_ip_address": ip, "client_user_agent": ua}


def _seed_tracking(db, tenant: Tenant) -> dict:
    """Seed M7 tracking demo data: one TrackingSource, two EventDestinations,
    and 100 ConversionEvents spread across the last 14 days.

    Idempotency
    -----------
    - TrackingSource:  skip if a source with name _TRACKING_SOURCE_NAME already
      exists for this tenant (matched by name + tenant_id).
    - EventDestinations:  skip if the source already has destinations (avoids
      re-adding on second run after the source was created).
    - ConversionEvents:  skip entire block if the source already has any events
      (count-based guard).  Deterministic event_id values prevent accidental
      duplication even if the guard is bypassed.

    Returns dict with counts.
    """
    from sqlalchemy import func as _func

    counts = {"tracking_sources": 0, "destinations": 0, "events_inserted": 0}

    # ── TrackingSource ─────────────────────────────────────────────────────
    source = db.scalar(
        select(TrackingSource).where(
            TrackingSource.tenant_id == tenant.id,
            TrackingSource.name == _TRACKING_SOURCE_NAME,
        )
    )
    if source is None:
        source = TrackingSource(
            tenant_id=tenant.id,
            name=_TRACKING_SOURCE_NAME,
            domain="easycep.com",
            public_token=_TRACKING_PUBLIC_TOKEN,
            is_active=True,
        )
        db.add(source)
        db.flush()
        print(f"  Created TrackingSource: {_TRACKING_SOURCE_NAME} ({source.id})")
        counts["tracking_sources"] = 1
    else:
        print(f"  TrackingSource already exists: {_TRACKING_SOURCE_NAME} ({source.id})")

    # ── EventDestinations ─────────────────────────────────────────────────
    existing_dest_count = db.scalar(
        select(_func.count()).select_from(EventDestination).where(
            EventDestination.tracking_source_id == source.id
        )
    ) or 0

    if existing_dest_count == 0:
        # meta_capi — consent_required=True (KVKK/GDPR strict)
        meta_dest = EventDestination(
            tenant_id=tenant.id,
            tracking_source_id=source.id,
            platform="meta_capi",
            config={
                "pixel_id": "1234567890123456",
                "action_source": "website",
            },
            vault_secret_ref="demo/tracking/meta_capi_access_token",
            consent_required=True,
            is_active=True,
        )
        # ga4_mp — consent_required=False (GA4 collects without strict consent)
        ga4_dest = EventDestination(
            tenant_id=tenant.id,
            tracking_source_id=source.id,
            platform="ga4_mp",
            config={
                "measurement_id": "G-DEMO000001",
            },
            vault_secret_ref="demo/tracking/ga4_api_secret",
            consent_required=False,
            is_active=True,
        )
        db.add_all([meta_dest, ga4_dest])
        db.flush()
        print(f"  Created EventDestination: meta_capi (consent_required=True)")
        print(f"  Created EventDestination: ga4_mp (consent_required=False)")
        counts["destinations"] = 2
    else:
        print(f"  EventDestinations already exist ({existing_dest_count} found) — skipping")

    # ── ConversionEvents ──────────────────────────────────────────────────
    existing_event_count = db.scalar(
        select(_func.count()).select_from(ConversionEvent).where(
            ConversionEvent.tracking_source_id == source.id
        )
    ) or 0

    if existing_event_count > 0:
        print(
            f"  ConversionEvents already exist ({existing_event_count} rows) — skipping"
        )
        db.commit()
        return counts

    # Generate 100 events spread across the last 14 days.
    # Day offset is index-based: idx // 7 gives 0–14 (14 days, ~7 events/day).
    _NUM_EVENTS = 100
    _TRACKING_END_DATE = _RICH_END_DATE  # reuse the same end-date anchor

    now_utc = datetime.now(timezone.utc)

    for idx in range(_NUM_EVENTS):
        # Spread events across 14 days: idx // 7 days back from end date
        day_offset = idx // 7  # 0 to 14
        event_date = _TRACKING_END_DATE - timedelta(days=day_offset)
        # Hour within the day: deterministic (idx % 24)
        event_hour = idx % 24
        event_dt = datetime(
            event_date.year, event_date.month, event_date.day,
            event_hour, (idx * 7) % 60, (idx * 13) % 60,
            tzinfo=timezone.utc,
        )
        event_time_iso = event_dt.isoformat()
        # Stable created_at slightly after event_time (seconds after = idx % 30)
        created_at_dt = event_dt.replace(second=min(59, (event_dt.second + idx % 30) % 60))
        created_at_iso = created_at_dt.isoformat()

        # Deterministic event_id — seed uses source token + index
        event_id = f"demo-evt-{_TRACKING_PUBLIC_TOKEN[:10]}-{idx:04d}"

        event_name, status, consent, forwarded_count, error = _event_profile(idx)

        # Identity signals → hashed user_data (no raw PII persisted) + match
        # quality score computed from the RAW profile, exactly as production does.
        raw_identity = _identity_profile(event_name, idx)
        user_data = hash_identity(raw_identity)
        match_quality = compute_match_quality(raw_identity)

        # custom_data — event-specific, no PII
        if event_name == "Purchase":
            value = float(150 + (idx % 5) * 50)  # 150, 200, 250, 300, 350
            custom_data = {
                "value": value,
                "currency": "TRY",
                "num_items": 1 + idx % 3,
                "order_id": f"ORDER-DEMO-{idx:04d}",
            }
        elif event_name == "AddToCart":
            custom_data = {
                "value": float(100 + (idx % 4) * 25),
                "currency": "TRY",
                "content_ids": [f"PROD-{(idx % 10) + 1:03d}"],
            }
        elif event_name == "InitiateCheckout":
            custom_data = {
                "value": float(200 + (idx % 3) * 75),
                "currency": "TRY",
                "num_items": 1 + idx % 4,
            }
        elif event_name == "ViewContent":
            custom_data = {
                "content_ids": [f"PROD-{(idx % 10) + 1:03d}"],
                "content_type": "product",
            }
        else:  # PageView
            custom_data = {
                "page_path": f"/demo/page-{(idx % 8) + 1}",
            }

        event_row = ConversionEvent(
            tenant_id=tenant.id,
            tracking_source_id=source.id,
            event_name=event_name,
            event_time=event_time_iso,
            event_id=event_id,
            user_data=user_data,
            custom_data=custom_data,
            consent=consent,
            match_quality=match_quality,
            status=status,
            forwarded_count=forwarded_count,
            error=error,
            created_at=created_at_iso,
        )
        db.add(event_row)
        counts["events_inserted"] += 1

    db.flush()
    db.commit()
    print(f"  Inserted {counts['events_inserted']} ConversionEvents")
    return counts


# ── Content Planner seeding (M11 — İçerik Planlayıcı) ───────────────────────────

# Demo content posts across the workflow statuses and channels.  scheduled_at
# is anchored to the rich demo window so the calendar shows realistic dates.
_CONTENT_POSTS = [
    {
        "title": "Yaz indirimi duyurusu",
        "body": (
            "☀️ Yaz geldi, fırsatlar kapıda! Seçili ürünlerde %40'a varan "
            "indirim hafta sonuna kadar EasyCep'te. Kaçırmayın!"
        ),
        "channels": ["instagram", "facebook"],
        "status": "scheduled",
        "day_offset": -2,
        "ai_assisted": True,
    },
    {
        "title": "Yeni sezon koleksiyonu",
        "body": (
            "Yeni sezon ürünleri raflardaki yerini aldı. En sevdiğin parçaları "
            "keşfetmek için profildeki bağlantıya göz at. 🛍️"
        ),
        "channels": ["instagram", "x", "tiktok"],
        "status": "approved",
        "day_offset": 1,
        "ai_assisted": False,
    },
    {
        "title": "Müşteri yorumu öne çıkarma",
        "body": (
            "\"Siparişim ertesi gün elimdeydi, paketleme harikaydı!\" — "
            "Mutlu müşterilerimizden biri daha. Sen de deneyimini paylaş. ⭐"
        ),
        "channels": ["facebook", "linkedin"],
        "status": "pending_approval",
        "day_offset": 3,
        "ai_assisted": False,
    },
    {
        "title": "Kargo bedava kampanyası",
        "body": (
            "📦 Bu hafta 250 TL ve üzeri tüm siparişlerde kargo ücretsiz! "
            "Sepetini doldur, fırsatı kaçırma."
        ),
        "channels": ["instagram", "facebook", "x"],
        "status": "draft",
        "day_offset": 5,
        "ai_assisted": True,
    },
    {
        "title": "Hafta sonu blog paylaşımı",
        "body": (
            "Bu hafta blogda: \"E-ticarette dönüşümü artıran 5 ürün fotoğrafı "
            "ipucu\". Tüm detaylar sitemizde. 📷"
        ),
        "channels": ["linkedin", "x"],
        "status": "draft",
        "day_offset": 7,
        "ai_assisted": False,
    },
    {
        "title": "Anneler Günü teşekkürü",
        "body": (
            "Tüm annelerin Anneler Günü kutlu olsun! 💐 Bu özel günde "
            "sevdiklerinize EasyCep ile ulaşın."
        ),
        "channels": ["instagram", "facebook"],
        "status": "published",
        "day_offset": -10,
        "ai_assisted": True,
    },
]


def _seed_content(db, tenant: Tenant) -> dict:
    """Seed M11 Content Planner demo data: a handful of ContentPosts across the
    full workflow (draft → pending_approval → approved → scheduled → published)
    and multiple social channels.

    Idempotency: skip entirely if the tenant already has any ContentPost.
    """
    from sqlalchemy import func as _func

    counts = {"content_posts": 0}

    existing = db.scalar(
        select(_func.count()).select_from(ContentPost).where(
            ContentPost.tenant_id == tenant.id
        )
    ) or 0
    if existing > 0:
        print(f"  ContentPosts already exist ({existing} rows) — skipping")
        return counts

    for spec in _CONTENT_POSTS:
        day_offset = spec["day_offset"]
        sched_date = _RICH_END_DATE + timedelta(days=day_offset)
        scheduled_at = (
            datetime(
                sched_date.year, sched_date.month, sched_date.day,
                10, 30, 0, tzinfo=timezone.utc,
            ).isoformat()
            if spec["status"] in ("scheduled", "published")
            else None
        )
        post = ContentPost(
            tenant_id=tenant.id,
            title=spec["title"],
            body=spec["body"],
            channels=list(spec["channels"]),
            scheduled_at=scheduled_at,
            status=spec["status"],
            ai_assisted=spec["ai_assisted"],
        )
        db.add(post)
        counts["content_posts"] += 1

    db.flush()
    db.commit()
    print(f"  Inserted {counts['content_posts']} ContentPosts")
    return counts


def _seed_budget(db, tenant: Tenant) -> dict:
    """Seed M12 Budget Planner demo data: one saved BudgetPlan for next month,
    with allocations computed from the seeded warehouse history.

    Idempotency: skip if the tenant already has any BudgetPlan.
    """
    from sqlalchemy import func as _func
    from ayaz.services.budget_planner import allocate_budget

    counts = {"budget_plans": 0}

    existing = db.scalar(
        select(_func.count()).select_from(BudgetPlan).where(
            BudgetPlan.tenant_id == tenant.id
        )
    ) or 0
    if existing > 0:
        print(f"  BudgetPlans already exist ({existing} rows) — skipping")
        return counts

    # Next month relative to the rich demo window.
    end = _RICH_END_DATE
    if end.month == 12:
        period_month = f"{end.year + 1}-01"
    else:
        period_month = f"{end.year}-{end.month + 1:02d}"

    total_budget = 150000.0
    try:
        allocations = allocate_budget(
            db,
            tenant.id,
            total_budget=total_budget,
            objective="balanced",
            lookback_days=90,
            currency="TRY",
            as_of=end,
        )
    except Exception as exc:  # pragma: no cover - defensive
        print(f"  Budget allocation failed ({exc}) — storing plan without snapshot")
        allocations = None

    plan = BudgetPlan(
        tenant_id=tenant.id,
        name=f"{period_month} Bütçe Planı",
        period_month=period_month,
        total_budget=total_budget,
        currency="TRY",
        objective="balanced",
        lookback_days=90,
        allocations=allocations,
        status="active",
    )
    db.add(plan)
    db.flush()
    counts["budget_plans"] = 1

    # Also seed the CURRENT month plan so Plan-vs-Gerçekleşen has real actuals.
    # Budget sized near the month's real spend so pacing reads realistically.
    current_month = f"{end.year}-{end.month:02d}"
    current_budget = 450000.0
    try:
        cur_alloc = allocate_budget(
            db, tenant.id, total_budget=current_budget, objective="balanced",
            lookback_days=90, currency="TRY", as_of=end,
        )
    except Exception:  # pragma: no cover
        cur_alloc = None
    cur_plan = BudgetPlan(
        tenant_id=tenant.id,
        name=f"{current_month} Bütçe Planı",
        period_month=current_month,
        total_budget=current_budget,
        currency="TRY",
        objective="balanced",
        lookback_days=90,
        allocations=cur_alloc,
        status="active",
    )
    db.add(cur_plan)
    db.flush()
    counts["budget_plans"] = 2

    db.commit()
    print(f"  Created 2 BudgetPlans: {plan.name}, {cur_plan.name}")
    return counts


# ── Social Inbox seeding (M13 — Sosyal Gelen Kutusu) ────────────────────────────

# (channel, kind, handle, name, text, sentiment, status, assignee, tags, day_offset, reply?)
_INBOX_MESSAGES = [
    ("instagram", "dm", "@ays_eylül", "Ayşe Eylül",
     "Siparişim ne zaman kargoya verilir? Çok merak ediyorum 😊", "neutral",
     "open", None, ["kargo"], 0, None),
    ("instagram", "comment", "@mehmet.kaya", "Mehmet Kaya",
     "Ürün elime ulaştı, kalitesine bayıldım! Teşekkürler 🙏", "positive",
     "resolved", "Destek Ekibi", ["övgü"],
     -1, "Çok teşekkür ederiz Mehmet Bey, sağlıkla kullanın! 💙"),
    ("facebook", "comment", "@zeynep.demir", "Zeynep Demir",
     "Kargo 5 gündür gelmedi, bu nasıl bir hizmet? Rezalet.", "negative",
     "pending", "Destek Ekibi", ["kargo", "şikayet"], 0,
     "Yaşadığınız aksaklık için çok üzgünüz Zeynep Hanım, hemen kontrol edip dönüyoruz."),
    ("x", "mention", "@burak_tech", "Burak",
     "@easycep uygulamanız harika olmuş, tebrikler 👏", "positive",
     "open", None, ["övgü"], 0, None),
    ("facebook", "dm", "@elif.yıldız", "Elif Yıldız",
     "İade sürecini başlatmak istiyorum, nasıl yapabilirim?", "neutral",
     "open", None, ["iade"], -1, None),
    ("instagram", "comment", "@can_oz", "Can Öz",
     "Beden tablosu yanlış, aldığım ürün çok küçük geldi.", "negative",
     "open", None, ["iade", "şikayet"], -2, None),
    ("tiktok", "comment", "@moda_sever", "Moda Sever",
     "Bu ürün hangi renklerde var? 😍", "positive", "open", None, [], 0, None),
    ("linkedin", "mention", "@ahmet.sahin", "Ahmet Şahin",
     "EasyCep ile çalışmak isteyen markalar için harika bir platform.", "positive",
     "resolved", "Pazarlama", ["işbirliği"], -3,
     "İlginiz için teşekkürler, işbirliği için size özelden yazıyoruz."),
    ("instagram", "dm", "@selin.ak", "Selin Ak",
     "Kampanya kodu çalışmıyor, yardımcı olur musunuz?", "negative",
     "pending", "Destek Ekibi", ["kampanya"], 0, None),
    ("youtube", "comment", "@tekno_review", "Tekno Review",
     "Videodaki ürünün linkini paylaşır mısınız?", "neutral", "open", None, [], -1, None),
    ("x", "dm", "@deniz.kara", "Deniz Kara",
     "Siparişim yanlış geldi, doğrusuyla değiştirebilir misiniz?", "negative",
     "open", None, ["iade"], 0, None),
    ("facebook", "comment", "@gül.şen", "Gül Şen",
     "Müşteri hizmetleriniz çok ilgili, çok memnun kaldım!", "positive",
     "resolved", "Destek Ekibi", ["övgü"], -2,
     "Güzel yorumunuz için teşekkürler Gül Hanım! 🌸"),
]


def _seed_inbox(db, tenant: Tenant) -> dict:
    """Seed M13 Social Inbox demo data: a spread of messages across channels,
    kinds, sentiments and statuses, with a few stored replies.

    Idempotency: skip if the tenant already has any SocialMessage.
    """
    from sqlalchemy import func as _func

    counts = {"messages": 0, "replies": 0}

    existing = db.scalar(
        select(_func.count()).select_from(SocialMessage).where(
            SocialMessage.tenant_id == tenant.id
        )
    ) or 0
    if existing > 0:
        print(f"  SocialMessages already exist ({existing} rows) — skipping")
        return counts

    for idx, spec in enumerate(_INBOX_MESSAGES):
        (channel, kind, handle, name, text, sentiment, status, assignee,
         tags, day_offset, reply) = spec
        recv = datetime(
            _RICH_END_DATE.year, _RICH_END_DATE.month, _RICH_END_DATE.day,
            9 + idx % 10, (idx * 7) % 60, 0, tzinfo=timezone.utc,
        ) + timedelta(days=day_offset)
        msg = SocialMessage(
            tenant_id=tenant.id,
            channel=channel,
            kind=kind,
            author_handle=handle,
            author_name=name,
            text=text,
            sentiment=sentiment,
            status=status,
            assignee=assignee,
            tags=list(tags),
            received_at=recv.isoformat(),
        )
        db.add(msg)
        db.flush()
        counts["messages"] += 1
        if reply:
            db.add(SocialReply(
                tenant_id=tenant.id,
                message_id=msg.id,
                body=reply,
                author=assignee or "Destek Ekibi",
                delivered=False,
                ai_assisted=False,
                created_at=(recv + timedelta(hours=1)).isoformat(),
            ))
            counts["replies"] += 1

    db.commit()
    print(f"  Inserted {counts['messages']} SocialMessages, {counts['replies']} replies")
    return counts


# ── Report seeding ─────────────────────────────────────────────────────────────

_REPORT_NAME = "AYAZ Demo — Aylik Performans Raporu"
_SHARED_REPORT_TOKEN = "ayaz-demo-report-token-000000001"


def _seed_reports(db, tenant: Tenant, user: User) -> dict:
    """Create one ReportDefinition with a SharedReport link.

    Guarded by _REPORTS_AVAILABLE — safe to call even if reports module is absent.
    Returns dict with counts.
    """
    counts = {"report_definitions": 0, "shared_reports": 0}
    if not _REPORTS_AVAILABLE:
        print("  reports model not available — skipping")
        return counts

    report_def = db.scalar(
        select(ReportDefinition).where(
            ReportDefinition.tenant_id == tenant.id,
            ReportDefinition.name == _REPORT_NAME,
        )
    )
    if report_def is None:
        report_def = ReportDefinition(
            tenant_id=tenant.id,
            name=_REPORT_NAME,
            created_by=user.id,
            config={
                "metrics": [
                    "spend", "impressions", "clicks",
                    "conversions", "conversion_value",
                    "ctr", "cpc", "cpa", "roas",
                ],
                "channels": ["google_ads", "meta_ads", "tiktok_ads"],
                "date_range_preset": "last_30_days",
                "sections": ["totals", "by_channel", "timeseries", "insights"],
                "brand_name": "AYAZ Demo Markasi",
                "logo_url": "https://ayaz.app/static/logo.png",
                "primary_color": "#6C47FF",
            },
        )
        db.add(report_def)
        db.flush()
        print(f"  Created ReportDefinition: {_REPORT_NAME} ({report_def.id})")
        counts["report_definitions"] = 1
    else:
        print(f"  ReportDefinition already exists ({report_def.id})")

    shared = db.scalar(
        select(SharedReport).where(
            SharedReport.public_token == _SHARED_REPORT_TOKEN
        )
    )
    if shared is None:
        shared = SharedReport(
            tenant_id=tenant.id,
            report_definition_id=report_def.id,
            public_token=_SHARED_REPORT_TOKEN,
            expires_at=None,
            is_active=True,
            view_count=0,
        )
        db.add(shared)
        db.flush()
        print(f"  Created SharedReport token={_SHARED_REPORT_TOKEN[:20]}... ({shared.id})")
        counts["shared_reports"] = 1
    else:
        print(f"  SharedReport already exists ({shared.id})")

    db.commit()
    return counts


# ── Main ──────────────────────────────────────────────────────────────────────


def run_seed() -> None:
    print("=" * 60)
    print("AYAZ Demo Seed Script  (enriched)")
    print("=" * 60)

    # Test DB connectivity
    try:
        with engine.connect() as conn:
            conn.execute(select(1))  # type: ignore[arg-type]
    except OperationalError as exc:
        print(f"\nERROR: Cannot connect to database.\n  {exc}")
        print(
            "\nTo run the seed you need a Postgres instance with the schema applied:\n"
            "  cd backend && alembic upgrade head\n"
            "  python -m scripts.seed_demo\n"
        )
        sys.exit(1)

    db = SessionLocal()

    summary: dict = {}

    try:
        # ── Step 1: Core OLTP ────────────────────────────────────────────────
        print("\n[1/7] Creating demo tenant, user, and membership...")
        tenant = _get_or_create_tenant(db)
        user = _get_or_create_user(db)
        _get_or_create_membership(db, user, tenant)
        db.commit()

        # ── Step 2: Connected accounts for all 3 rich channels ───────────────
        print("\n[2/7] Creating connected accounts (google_ads, meta_ads, tiktok_ads)...")
        channel_accounts: dict[str, ConnectedAccount] = {}
        for ch_spec in _CHANNEL_SPECS:
            acc = _get_or_create_connected_account(
                db, tenant,
                platform=ch_spec["platform"],
                external_id=ch_spec["account_ext_id"],
                display_name=ch_spec["account_display"],
            )
            channel_accounts[ch_spec["channel_key"]] = acc

        # Also create the legacy fixture accounts (sample + google_ads fixture)
        sample_account = _get_or_create_connected_account(
            db, tenant,
            platform=Platform.sample,
            external_id="ACC-001",
            display_name="Sample Ad Account (fixture)",
        )
        gads_fixture_account = _get_or_create_connected_account(
            db, tenant,
            platform=Platform.google_ads,
            external_id="1234567890",
            display_name="Google Ads Account (fixture)",
        )
        db.commit()

        # ── Step 3: Legacy fixture syncs (preserved from original seed) ──────
        print("\n[3/7] Syncing legacy 'sample' connector (fixture mode)...")
        sample_result = sync_connected_account(
            db,
            account=sample_account,
            since=_SYNC_SINCE,
            until=_SYNC_UNTIL,
        )
        print(
            f"  sample: inserted={sample_result['inserted']} "
            f"updated={sample_result['updated']} "
            f"records={sample_result['records_processed']}"
        )

        print("\n[4/7] Syncing legacy 'google_ads' connector (fixture mode)...")
        gads_config = ConnectorConfig(
            tenant_id=str(tenant.id),
            connected_account_id=str(gads_fixture_account.id),
            external_account_id=gads_fixture_account.external_account_id,
            platform_key="google_ads",
            vault_secret_ref="",
            extra={"customer_id": "1234567890", "currency": "USD"},
        )
        fixture_connector = _FixtureGoogleAdsConnector(
            config=gads_config,
            fixture_path=_GOOGLE_ADS_FIXTURE,
        )

        gads_fixture_account.sync_status = SyncStatus.syncing
        db.flush()

        caps = fixture_connector.capabilities()
        all_records = []
        for stream in caps.supported_streams:
            raw = fixture_connector.fetch(
                stream=stream, since=_SYNC_SINCE, until=_SYNC_UNTIL
            )
            all_records.extend(fixture_connector.normalize(raw))

        gads_channel = _get_or_create_channel(db, "google_ads")
        g_inserted = 0
        g_updated = 0
        for rec in all_records:
            _ensure_dim_date(db, rec.date_key)
            campaign = _get_or_create_campaign(
                db, tenant.id, gads_channel, rec.campaign_id, rec.campaign_name
            )
            adset = _get_or_create_adset(
                db, tenant.id, campaign, rec.adset_id, rec.adset_name
            )
            ad = _get_or_create_ad(
                db, tenant.id, adset, rec.ad_id, rec.ad_name
            )
            _, created = _upsert_fact(
                db,
                tenant_id=tenant.id,
                connected_account_id=gads_fixture_account.id,
                channel=gads_channel,
                campaign=campaign,
                adset=adset,
                ad=ad,
                record=rec,
            )
            if created:
                g_inserted += 1
            else:
                g_updated += 1

        if all_records:
            latest = max(r.date_key for r in all_records)
            gads_fixture_account.watermark = latest.isoformat()
        gads_fixture_account.sync_status = SyncStatus.success
        db.commit()
        print(
            f"  google_ads fixture: inserted={g_inserted} updated={g_updated} "
            f"records={len(all_records)}"
        )

        # ── Step 5: Rich 45-day fact data with anomalies ─────────────────────
        print("\n[5/7] Generating 45 days of rich FactDailyMetrics (3 channels, 7 campaigns)...")
        print(
            f"  Date range: {_RICH_START_DATE} — {_RICH_END_DATE}  "
            f"(anomaly window: {_RICH_START_DATE + timedelta(days=_ANOMALY_START_OFFSET)} — {_RICH_END_DATE})"
        )
        fact_inserted, fact_updated = _seed_rich_facts(db, tenant, channel_accounts)
        print(f"  Rich facts: inserted={fact_inserted}  updated={fact_updated}")
        summary["fact_inserted"] = fact_inserted
        summary["fact_updated"] = fact_updated

        # ── Step 5b: Ad-level creative facts (3 extra ads per campaign x 3 channels) ──
        print(
            f"\n[5b/7] Seeding ad-level creative facts "
            f"(3 extra ads per campaign, recent 14 days: {_AD_LEVEL_START} — {_AD_LEVEL_END})..."
        )
        ad_inserted, ad_updated = _seed_ad_level_facts(db, tenant, channel_accounts)
        print(f"  Ad-level facts: inserted={ad_inserted}  updated={ad_updated}")
        summary["ad_fact_inserted"] = ad_inserted
        summary["ad_fact_updated"] = ad_updated
        print("  Ad profiles seeded:")
        print("    google_ads / Brand Search:      Video-Indirim(winner), Statik-Marka(mid), Responsive-Sezon(loser)")
        print("    meta_ads   / Retargeting:       Video-Sepet(winner), Statik-Indirim(mid), Koleksiyon(loser, 0 conv)")
        print("    tiktok_ads / Viral Creative:    Duet-Urun(winner), Statik-Flash(mid), Spark-Dusuk(loser)")

        # ── Step 5c: Tracking (M7) demo data ─────────────────────────────────
        print(
            f"\n[5c/7] Seeding M7 tracking data "
            f"(TrackingSource + 2 EventDestinations + 100 ConversionEvents)..."
        )
        tracking_counts = _seed_tracking(db, tenant)
        summary["tracking"] = tracking_counts
        print(
            f"  Tracking: sources={tracking_counts['tracking_sources']}  "
            f"destinations={tracking_counts['destinations']}  "
            f"events_inserted={tracking_counts['events_inserted']}"
        )

        # ── Step 5d: Content Planner (M11) demo data ─────────────────────────
        print("\n[5d/7] Seeding M11 content planner data (ContentPosts)...")
        content_counts = _seed_content(db, tenant)
        summary["content"] = content_counts
        print(f"  Content: posts={content_counts['content_posts']}")

        # ── Step 5e: Budget Planner (M12) demo data ──────────────────────────
        print("\n[5e/7] Seeding M12 budget planner data (BudgetPlan)...")
        budget_counts = _seed_budget(db, tenant)
        summary["budget"] = budget_counts
        print(f"  Budget: plans={budget_counts['budget_plans']}")

        # ── Step 5f: Social Inbox (M13) demo data ────────────────────────────
        print("\n[5f/7] Seeding M13 social inbox data (SocialMessage + replies)...")
        inbox_counts = _seed_inbox(db, tenant)
        summary["inbox"] = inbox_counts
        print(f"  Inbox: messages={inbox_counts['messages']} replies={inbox_counts['replies']}")

        # ── Step 6: Feeds ─────────────────────────────────────────────────────
        print("\n[6/7] Seeding product feed (FeedSource + 2 FeedChannels + rules)...")
        feed_counts = _seed_feeds(db, tenant)
        summary["feeds"] = feed_counts
        print(
            f"  Feed sources={feed_counts['feed_sources']}  "
            f"products={feed_counts['products']}  "
            f"channels={feed_counts['channels']}  "
            f"rules={feed_counts['rules']}"
        )

        # ── Step 7: Insights ──────────────────────────────────────────────────
        print("\n[7/7] Generating insights (running all detectors)...")
        insight_counts = generate_insights(
            db,
            tenant_id=tenant.id,
            as_of_date=_RICH_END_DATE,
            lookback_days=45,
        )
        db.commit()
        summary["insights"] = insight_counts
        print(
            f"  Insights: new_info={insight_counts['new_info']}  "
            f"new_warning={insight_counts['new_warning']}  "
            f"new_critical={insight_counts['new_critical']}  "
            f"skipped={insight_counts['skipped']}"
        )

        # ── Optional: Reports ─────────────────────────────────────────────────
        print("\n[bonus] Seeding ReportDefinition + SharedReport...")
        report_counts = _seed_reports(db, tenant, user)
        summary["reports"] = report_counts

    finally:
        db.close()

    # ── Summary ───────────────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("Seed complete — full demo data summary")
    print("=" * 60)
    print()
    print("Fact rows (rich 45-day, 3 channels, 7 campaigns):")
    print(f"  Inserted : {summary.get('fact_inserted', 0)}")
    print(f"  Updated  : {summary.get('fact_updated', 0)}")
    print()
    print("Ad-level creative facts (3 extra ads x 3 campaigns, 14 days):")
    print(f"  Inserted : {summary.get('ad_fact_inserted', 0)}")
    print(f"  Updated  : {summary.get('ad_fact_updated', 0)}")
    print()
    print("Anomalies injected (last 7 days):")
    print("  google_ads / 'Brand Search'    — ROAS drop  (conv_value x 0.35)")
    print("  meta_ads   / 'Retargeting'     — Spend spike (cost x 3.2)")
    print("  tiktok_ads / 'Viral Creative'  — Zero conversions")
    print()
    trk = summary.get("tracking", {})
    print("Tracking (M7):")
    print(f"  TrackingSources : {trk.get('tracking_sources', 0) or '(already existed)'}")
    print(f"  Destinations    : {trk.get('destinations', 0) or '(already existed)'}")
    print(f"  Events inserted : {trk.get('events_inserted', 0)}")
    print(f"  Collect URL     : /api/v1/tracking/collect/{_TRACKING_PUBLIC_TOKEN}")
    print()
    feeds = summary.get("feeds", {})
    print("Product feeds:")
    print(f"  FeedSources : {feeds.get('feed_sources', 0) or '(already existed)'}")
    print(f"  Products    : {feeds.get('products', 0)}")
    print(f"  Channels    : {feeds.get('channels', 0) or '(already existed)'}")
    print(f"  Rules       : {feeds.get('rules', 0) or '(already existed)'}")
    print(f"  Google Shopping URL  : /api/v1/feeds/public/{_GOOGLE_FEED_TOKEN}")
    print(f"  Meta Catalog URL     : /api/v1/feeds/public/{_META_FEED_TOKEN}")
    print()
    ins = summary.get("insights", {})
    print("Insights generated:")
    print(f"  info={ins.get('new_info', 0)}  warning={ins.get('new_warning', 0)}  critical={ins.get('new_critical', 0)}  skipped={ins.get('skipped', 0)}")
    print()
    rpts = summary.get("reports", {})
    print("Reports:")
    print(f"  Definitions : {rpts.get('report_definitions', 0) or '(already existed)'}")
    print(f"  Shared link : /api/v1/reports/public/{_SHARED_REPORT_TOKEN}")
    print()
    print("Demo login credentials:")
    print(f"  Email    : {DEMO_EMAIL}")
    print(f"  Password : {DEMO_PASSWORD}")
    print()
    print("To obtain a JWT:")
    print(
        f'  curl -s -X POST http://localhost:8000/api/v1/auth/login \\\n'
        f'    -H "Content-Type: application/json" \\\n'
        f'    -d \'{{"email":"{DEMO_EMAIL}","password":"{DEMO_PASSWORD}"}}\''
    )
    print("=" * 60)


if __name__ == "__main__":
    run_seed()
